### ISSUE TITLE
7 ISO codes are invalid

### ISSUE THREAD

**Issue by arietis** [iziz/libPhoneNumber-iOS#103]
Hello!
AQ, BV, GS, HM, PN, TF and UM region codes are marked as invalid so we can't get calling codes. But according to https://en.wikipedia.org/wiki/List_of_country_calling_codes it looks valid. Would be nice to get internal libPhoneNumber-iOS support instead of reinventing the wheel for such codes everytime. :)
Thanks!

**Comment by iziz** [comment]
Sorry for late response.
libPhoneNumber-iOS is port from "libphonenumber".
Please visit https://github.com/googlei18n/libphonenumber and request metadata for AQ, BV, GS, HM, PN, TF and UM region codes.
Thanks :)
