### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by TwimbeeCherif** [iziz/libPhoneNumber-iOS#106]
When I run the scheme libPhoneNumberSampleSwift of libPhoneNumber.xcodeproj I get :

dyld: Library not loaded: @rpath/libPhoneNumber.framework/libPhoneNumber
  Referenced from: /private/var/mobile/Containers/Bundle/Application/BB28F277-C7AD-4807-94D0-E5E8C3316C7B/libPhoneNumberSampleSwift.app/libPhoneNumberSampleSwift
  Reason: image not found
(lldb) 

I am using Xcode Version 7.0.1 (7A1001)

**Comment by iziz** [comment]
Maybe "libPhoneNumber.framework" was missing. (that's strange)
Add "libPhoneNumber.framework" in target's "Embedded Binaries".
