### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ldiqual** [iziz/libPhoneNumber-iOS#125]
I couldn't find a way to know what's new in 0.8.11 without looking at the diff (which is often verbose and not easy to understand for people who don't know the codebase).

Would you mind adding a changelog or add tag descriptions for each release?

**Comment by iziz** [comment]
Sorry for late (was updated change log)

**Comment by ldiqual** [comment]
@iziz I'm confused, where did you add a changelog?
