### ISSUE TITLE
issue in formatting of phone number of some specific country like france,Germeny In iOS

### ISSUE THREAD

**Issue by alokducs** [iziz/libPhoneNumber-iOS#126]
i was trying to use the phone Number formatting for France,and Germany using this Function 

    NBAsYouTypeFormatter *f = [[NBAsYouTypeFormatter alloc] initWithRegionCode:@"FR"];
    NSLog(@"%@", [f inputDigit:@"6"]); 
    NSLog(@"%@", [f inputDigit:@"7"]); 
    NSLog(@"%@", [f inputDigit:@"8"]); 
    NSLog(@"%@", [f inputDigit:@"9"]); 
    NSLog(@"%@", [f inputDigit:@"0"]); 
    NSLog(@"%@", [f inputDigit:@"1"]); 

    // Note this is how a US local number (without area code) should be formatted.
    NSLog(@"%@", [f inputDigit:@"2"]); 
    NSLog(@"%@", [f inputDigit:@"3"]); 
    NSLog(@"%@", [f inputDigit:@"4"]); 

    NSLog(@"%@", [f inputString:@"678901234"]); // 6 78 90 12 34  // it Should be like this 

But i was not able to get the correct phone Formatting

Please Look into it.

-Alok Dubey

**Comment by iziz** [comment]
I think mobile number format should be "0X XX XX XX XX" in France
![untitled-1](https://cloud.githubusercontent.com/assets/318647/13781758/cbea081c-eb07-11e5-9a97-615361b70d7b.png)

So, 0678901234 will works fine. 
(And some metadata was updated via https://github.com/googlei18n/libphonenumber.)
