### ISSUE TITLE
Parsing international phone number w/ unknown locale is broken

### ISSUE THREAD

**Issue by ryancarlson** [iziz/libPhoneNumber-iOS#128]
Per documentation in the code, this should be possible:

``` c
            NBPhoneNumber *phoneNumber = [sharedUtil parse:@"+33"
                                             defaultRegion:nil
                                                     error:nil];
```

but returns an error because:
- NBPhoneNumberUtil.parse :numberToParse :defaultRegion :error requires a leading plus to be called when parsing an international number w/ nil passed as :defaultRegion.  The docs on this method explicitly say this is allowed:
- https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber/NBPhoneNumberUtil.m#L3261

> If the number is guaranteed to start with a '+' followed by the country calling code, then 'ZZ' or nil can be supplied.
- NBPhoneNumberUtil.parseHelper :numberToParse :defaultRegion :keepRawInput :checkRegion :error calls `isViablePhoneNumber` which will always return NO if the string starts with a '+'.  This is stated here:
  -https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber/NBPhoneNumberUtil.m#L561

> This method does not require the number to be normalized in advance - but does assume that leading non-number symbols have been removed

**Comment by ryancarlson** [comment]
My use case here is to "validate as the user goes".  If I wait until there are at least 6 characters then this works, but if there are fewer then it fails.

**Comment by iziz** [comment]
Sorry I missed this issue. You can use AsYouTypeFormatter
