### ISSUE TITLE
Wrong Phone Code 

### ISSUE THREAD

**Issue by lethianqt94** [iziz/libPhoneNumber-iOS#129]
I recognized that the if the calling code is more than 3 digits. Your lib always return the first digit. For example, American Samoa's is +1684, Anguilla's is +1264, but it gave me all + 1. Do you have any solution?

**Comment by iziz** [comment]
Sorry for late (was very busy T.T)
Could you give me some sample phone numbers ?
And please check with below link (googles phonenumber demo page)
- https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by anlt** [comment]
Here you are. +1 684 633 0001. Thanks for reply.

**Comment by iziz** [comment]
```
INPUT

Phonenumber : 16846330001
Specify a Default Country : AS
```

Shows below is this is right ?

```
OUTPUT

****Parsing Result:****
{"country_code":1,"national_number":6846330001,"raw_input":"16846330001","country_code_source":10,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: AS
Result from getNumberType(): FIXED_LINE

****Formatting Results:**** 
E164 format: +16846330001
Original format: 1 684-633-0001
National format: (684) 633-0001
International format: +1 684-633-0001
Out-of-country format from US: 1 (684) 633-0001
Out-of-country format from Switzerland: 00 1 684-633-0001
```

**Comment by anlt** [comment]
Thanks for you efforts. That's right. ^^

**Comment by wudan3551** [comment]
so the problem is solved ? i found same one +1264

**Comment by emacslisp** [comment]
problem is not resolved, it still get +1 not +1-684
