### ISSUE TITLE
Build error when using @import when modules are disabled

### ISSUE THREAD

**Issue by master-nevi** [iziz/libPhoneNumber-iOS#132]
Build error in `NBPhoneNumberDefines.h`:
```
/var/folders/01/qpbck_0j79g966q8qkfw1ch0002rry/T/CocoaPods/Lint/Pods/Headers/Private/libPhoneNumber-iOS/NBPhoneNumberDefines.h:7:1: error: use of '@import' when modules are disabled
@import Foundation;
^
```

`#import <Foundation/Foundation.h>` can be used for static libs and dynamic frameworks since all #import and #include directives are mapped to use @import automatically if modules are used: http://stackoverflow.com/questions/18947516/import-vs-import-ios-7

**Comment by master-nevi** [comment]
I can PR an update for this if you agree with the issue.

**Comment by ashoemaker** [comment]
👍

**Comment by iziz** [comment]
Sure, please

**Comment by master-nevi** [comment]
See PR: https://github.com/iziz/libPhoneNumber-iOS/pull/133

**Comment by iziz** [comment]
Thanks
