### ISSUE TITLE
Shows alert in case of correct number 

### ISSUE THREAD

**Issue by nil4587** [iziz/libPhoneNumber-iOS#134]
Hi,
I'm using this library to check the valid mobile within my application for selected country. Today, I've placed one mobile number '8447211220' for India but it shows that the entered number is wrong for selected country though it is a valid mobile number and I'm having it.

Please help for this as soon as possible.

Thanks,

**Comment by iziz** [comment]
Could you show me your checking code ?

**Comment by nil4587** [comment]
Hi,
Sorry for delay just because of some priority tasks. Here, I'm going to place my actual development code.

-=====================================================================-
            
            NSString *ccode = [self.txtCountryCode.text stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
            NSString *mobilenumber = [self.txtMobile.text stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
            
            NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
            NSError *anError = nil;
            NBPhoneNumber *myNumber = [phoneUtil parse:self.txtMobile.text
                                         defaultRegion:[self.dictCountryInfo valueForKey:ISO_CODE_KEY] error:&anError];
            if (anError == nil)
            {
                NBEPhoneNumberType numberType = [phoneUtil getNumberType:myNumber];
                NBEValidationResult validateResult = [phoneUtil isPossibleNumberWithReason:myNumber error:&anError];
                DLog(@"NumberType : %ld",(long)numberType);
                
                if (numberType == NBEPhoneNumberTypeMOBILE && validateResult == NBEValidationResultIS_POSSIBLE)
                {
                    NSString *title = NSLocalizedString(@"MOBILE_CONFIRM_TITLE",nil);
                    NSString *message = [NSString stringWithFormat:NSLocalizedString(@"MOBILE_CONFIRM_MSG",nil),[phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatINTERNATIONAL error:&anError]];
                    
                    SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
                    if ([GET_VALUE_FOR_KEY(SOUND_OTHERMSG_BEEP_KEY) boolValue]) {
                        NSString *path = [[NSBundle mainBundle] pathForResource:TM_WRNG_LOC_SOUND_KEY ofType:@"aiff"];
                        alert.soundURL = [NSURL fileURLWithPath:path];
                    }
                    [alert addButton:@"Yes" actionBlock:^{
                        dispatch_async(dispatch_get_main_queue(), ^{
                            [self callAuthenticateUserWebservice:mobilenumber andCountryCode:ccode];
                        });
                    }];
                    [alert addButton:@"No" actionBlock:^{
                        dispatch_async(dispatch_get_main_queue(), ^{
                            [self.txtMobile becomeFirstResponder];
                        });
                    }];
                    [alert showQuestion:self title:title subTitle:message closeButtonTitle:nil duration:0.0];
                    dispatch_async(dispatch_get_main_queue(),^{
                        [Instance_Manager hideProgressiveHUD];
                    });
                }
                else {
                    if (validateResult == NBEValidationResultINVALID_COUNTRY_CODE) {
                        [[CommonFunction sharedInstance] showAlertMessageWithTitle:NSLocalizedString(@"MSG_ALERT_TITLE", nil) message:[NSString stringWithFormat:NSLocalizedString(@"COUNTRY_CODE_VALIDATE_MSG", nil),[self.dictCountryInfo valueForKey:MOBILE_CODE_KEY]]];
                    }
                    else if (validateResult == NBEValidationResultTOO_SHORT) {
                        [[CommonFunction sharedInstance] showAlertMessageWithTitle:NSLocalizedString(@"MSG_ALERT_TITLE", nil) message:[NSString stringWithFormat:NSLocalizedString(@"MOBILE_PHONE_NUMBER_SHORT_MSG", nil),[self.dictCountryInfo valueForKey:COUNTRY_KEY]]];
                    }
                    else if (validateResult == NBEValidationResultTOO_LONG) {
                        [[CommonFunction sharedInstance] showAlertMessageWithTitle:NSLocalizedString(@"MSG_ALERT_TITLE", nil) message:[NSString stringWithFormat:NSLocalizedString(@"MOBILE_PHONE_NUMBER_LONG_MSG", nil),[self.dictCountryInfo valueForKey:COUNTRY_KEY]]];
                    }
                    else {
                        [[CommonFunction sharedInstance] showAlertMessageWithTitle:NSLocalizedString(@"MSG_ALERT_TITLE", nil) message:[NSString stringWithFormat:NSLocalizedString(@"INSERT_VALID_MOBILE_MSG", nil),[self.dictCountryInfo valueForKey:COUNTRY_KEY]]];
                    }
                    dispatch_async(dispatch_get_main_queue(),^{
                        [Instance_Manager hideProgressiveHUD];
                    });
                }
            }
            else {
                DLog(@"Error : %@", [anError localizedDescription]);
                [[CommonFunction sharedInstance] showAlertMessageWithTitle:NSLocalizedString(@"MSG_ALERT_TITLE", nil) message:[NSString stringWithFormat:NSLocalizedString(@"INSERT_VALID_MOBILE_MSG", nil),[self.dictCountryInfo valueForKey:COUNTRY_KEY]]];
                dispatch_async(dispatch_get_main_queue(),^{
                    [Instance_Manager hideProgressiveHUD];
                });
            }

-=====================================================================-

So, please check and let me know what's the issue. Here is the mobile number for which I'm getting an error. : 8447211220 and country code is : 91

Thanks,

**Comment by nil4587** [comment]
Hi,
Thanks for your reply but somehow I got the solution. Actually I was considering only "NBEPhoneNumberTypeMOBILE" but the number that I have mentioned was "NBEPhoneNumberTypeFIXED_LINE_OR_MOBILE" and so I have considered this type as well from now onwards.

So, I'm going to close the issue.

Thanks,
