### ISSUE TITLE
Brazil numbers are show as invalid when they are really valid

### ISSUE THREAD

**Issue by benjitastic** [iziz/libPhoneNumber-iOS#135]
This 2 numbers are both valid Brazilian numbers. The extra 9 is a recent change in phone numbers.

```
+556899069724
+5568999069724
```

However libPhoneNumber-iOS says that the 2nd one is invalid. The original libPhoneNumber library identifies both numbers correctly as being valid.

Is this port of the libPhoneNumber different and maybe missing the latest awareness of Brazilian phone numbers?

Thanks

**Comment by fgsguedes** [comment]
Even on Google's libphoneNumber the ninth digit on area codes ranging from 61 ~ 69 was just implemented 15 days ago, so it still have to be ported here.
Pull request #137 ports only the changes from 7.4.x relative to Brazilian area codes but probably not all of them.

**Comment by iziz** [comment]
metadata was updated from 7.4.1

**Comment by luciocouto** [comment]
Hi, now i have the same problem with the code ranging from 41 ~ 59.

I Know metadata 7.7.4 is updated, from google. Is there any prevision to update it?
