### ISSUE TITLE
numbers with leading zeros not valid

### ISSUE THREAD

**Issue by mlostekk** [iziz/libPhoneNumber-iOS#139]
when i have a number starting with 0049, the phone number util does not recognize this number as a valid german number. 

is this is bug or intended behavior? 

Example:
the number
"004915066666666"

will become
NBPhoneNumber.nationalNumber = "4915066666666"
NBPhoneNumber.countryCode = "1"

**Comment by iziz** [comment]
Could show tell me your test code ?
And check with below link
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by blazierkyle** [comment]
First off - I love this library. Thank you so much for all your hard work on it!

Unfortunately, I am also having this issue. For example: 0066-33-132432 for region = Japan ("JP") is a valid toll-free number in the link you provided, but not by this library.

Thank you!

**Comment by iziz** [comment]
Ooops I will port that changes. Thank you very much.

**Comment by iziz** [comment]
Please check with latest code from github (not cocoapods)
