### ISSUE TITLE
Some Phone numbers not working.. starting with 7425 for india

### ISSUE THREAD

**Issue by aki263** [iziz/libPhoneNumber-iOS#140]
7425861236 or infact any numbers starting with 7425 for india

**Comment by aki263** [comment]
Please update the library, it is very important to address this issue, the error was in android library also but they have now updated their library, please do the same changes here also. 

Thanks in advance.

**Comment by iziz** [comment]
Updated metadata from libphonenumber 7.4.4
Please check and close :)

**Comment by aki263** [comment]
Thanks a ton. Everything is working now.
