### ISSUE TITLE
Wrong Kuwaiti Number

### ISSUE THREAD

**Issue by nahlam** [iziz/libPhoneNumber-iOS#141]
I'm using last Cocoapods version of the lib and i'm getting that any number at Kuwait starts with 62 is wrong although they are valid
for example +9656222**** returns not valid number

**Comment by iziz** [comment]
Pleae check with below link
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by nahlam** [comment]
It's valid 
<img width="502" alt="screen shot 2016-07-13 at 6 01 04 pm" src="https://cloud.githubusercontent.com/assets/5165453/16810367/e70da85e-4923-11e6-87ae-2c6804d7b9f7.png">

**Comment by nahlam** [comment]
It's valid check this 
<img width="502" alt="screen shot 2016-07-13 at 6 01 04 pm copy" src="https://cloud.githubusercontent.com/assets/5165453/16810601/c066ed5e-4924-11e6-8eff-c2519ee7da00.png">

**Comment by iziz** [comment]
OK I will check it.

**Comment by iziz** [comment]
I checked below code, and it return "YES"
```
    NBPhoneNumber *myNumber = [phoneUtil parse:@"+96562221234" defaultRegion:nil error:&anError];
    if (anError == nil)
    {
        NSLog(@"isValidPhoneNumber ? [%@]", [phoneUtil isValidNumber:myNumber] ? @"YES":@"NO");
        NSLog(@"E164          : %@", [phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatE164 error:&anError]);
        NSLog(@"INTERNATIONAL : %@", [phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatINTERNATIONAL error:&anError]);
        NSLog(@"NATIONAL      : %@", [phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatNATIONAL error:&anError]);
        NSLog(@"RFC3966       : %@", [phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatRFC3966 error:&anError]);
    }
```

Any problem ?
