### ISSUE TITLE
Chinese PhoneNumber Check Wrong

### ISSUE THREAD

**Issue by hustdestiny** [iziz/libPhoneNumber-iOS#142]
My phone number is +86  17196622520,
I call  the method `isValidNumber:` ,it return NO .
Here is my Screenshot:
![fe4cc1e0-3953-433d-af7a-a770b1467e4e](https://cloud.githubusercontent.com/assets/14134107/16981633/0943aca0-4e9e-11e6-97ae-8c1d5bf4c9eb.png)

**Comment by iziz** [comment]
OK I will check it.

**Comment by iziz** [comment]
Done (Updated metadata and release 0.8.15), and works fine now.
Thanks.

**Comment by hustdestiny** [comment]
Thank you very much!
