### ISSUE TITLE
-[NBPhoneMetadataGR init] crash

### ISSUE THREAD

**Issue by n3trino** [iziz/libPhoneNumber-iOS#143]
The stack of the crash:

Crashed: NSOperationQueue 0x156699b0 :: Fetch Contacts (QOS: UTILITY)
0  libobjc.A.dylib                0x22fd3a86 objc_msgSend + 5
1  libPhoneNumber_iOS             0x6576ad -[NBPhoneMetadataGR init](NBMetadataCore.m:13951)
2  libPhoneNumber_iOS             0x66caf7 -[NBMetadataHelper getMetadataForRegion:](NBMetadataHelper.m:231)
3  libPhoneNumber_iOS             0x67ac8b -[NBPhoneNumberUtil parseHelper:defaultRegion:keepRawInput:checkRegion:error:](NBPhoneNumberUtil.m:3468)
4  libPhoneNumber_iOS             0x67a52f -[NBPhoneNumberUtil parse:defaultRegion:error:](NBPhoneNumberUtil.m:3283)
5  wover                          0x9e770 specialized CNContact.mobilePhones(String?) -> [String](WOVCNContact+Extensions.swift:48)
6  wover                          0x9d9fc @objc CNContact.mobilePhones(String?) -> [String](WOVCNContact+Extensions.swift)
7  wover                          0x9d534 CNContact.isValidContact() -> Bool (WOVCNContact+Extensions.swift:22)
8  wover                          0x9d5fc @objc CNContact.isValidContact() -> Bool (WOVCNContact+Extensions.swift)
9  wover                          0xd3b10 WOVFetchContactsOperation.(execute() -> ()).(closure #1) (WOVFetchContactsOperation.swift:47)
10 CoreFoundation                 0x23729273 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 86
11 CoreFoundation                 0x23729167 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 190
12 Contacts                       0x29db47bf -[CNDataMapperContactStore enumerateContactsAndMatchInfoWithFetchRequest:error:usingBlock:] + 286
13 Contacts                       0x29da082b -[CNContactStore enumerateContactsWithFetchRequest:error:usingBlock:] + 86
14 wover                          0xd2fb8 WOVFetchContactsOperation.execute() -> () (WOVFetchContactsOperation.swift:50)
15 wover                          0xa2d3c WOVOperation.main() -> () (WOVOperation.swift:316)
16 wover                          0xa319c @objc WOVOperation.main() -> () (WOVOperation.swift)
17 Foundation                     0x23f71f8f -[__NSOperationInternal _start:] + 774
18 wover                          0xa292c @objc WOVOperation.start() -> () (WOVOperation.swift:300)
19 Foundation                     0x24020b0d __NSOQSchedule_f + 192
20 libdispatch.dylib              0x233a5e7f _dispatch_queue_drain + 1762
21 libdispatch.dylib              0x2339ee17 _dispatch_queue_invoke + 282
22 libdispatch.dylib              0x233a720d _dispatch_root_queue_drain + 400
23 libdispatch.dylib              0x233a707b _dispatch_worker_thread3 + 94
24 libsystem_pthread.dylib        0x2353ae0d _pthread_wqthread + 1024
25 libsystem_pthread.dylib        0x2353a9fc start_wqthread + 8

Any thoughts on this one?

**Comment by iziz** [comment]
Please show me some sample code block
