### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by medisean** [iziz/libPhoneNumber-iOS#146]
I made a [swift3](https://github.com/teambition/libPhoneNumber-iOS) fork & branch. If you make a swift3 branch I can submit a pull request.

**Comment by iziz** [comment]
Done. Thanks!

**Comment by gmansata6290** [comment]
I have added this library in my exisiting swift 3 project using cocoapods as pod 'libPhoneNumber-iOS'. 1) Now the problem is I can't access NBTextField class. 2) As shown in the example for Swift Demo I can't import libPhoneNumberiOS in swift.

**Comment by dmaclach** [comment]
Can you give us more details on how to repro? Step by step would be great.
