### ISSUE TITLE
Fail parsing National Italian Number 

### ISSUE THREAD

**Issue by jacomartin** [iziz/libPhoneNumber-iOS#149]
I pass a National number starting with 046***** and the return is +39 46**** like if the number was from CellPhone company. I specify the country id.

Thanks for these library, it's useful.

**Comment by iziz** [comment]
Please tell me some 'sample phone number' and expected result and real result.

**Comment by jacomartin** [comment]
Sure,

Here some Number:

0464 565073

0461 346781

0461 559047


Expected result:

+39 0464 565073

+39 0461 346781

+39 0461 559047


Real Result:

+39464 565073

+39461 346781

+39461 559047


Also I checked your code and I found the issue, you use a longInt for save and return the number, that cut all the 0 from Italian's prefix number. I suggest to use string or other type to solve this problem.






On Tue, Oct 18, 2016 at 4:00 PM +0200, "iziz" <notifications@github.com> wrote:












Please tell me some 'sample phone number' and expected result and real result.

**Comment by iziz** [comment]
Maybe latest code from github will be work fine. (I will update pod update next week)
```
    NSError *anError = nil;
    NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
    NBPhoneNumber *phoneNumberUS = [phoneUtil parse:@"0464 565073" defaultRegion:@"IT" error:&anError];
    if (anError) {
        NSLog(@"err [%@]", [anError localizedDescription]);
    }
    else {
        NSLog(@"INTERNATIONAL : %@", [phoneUtil format:phoneNumberUS numberFormat:NBEPhoneNumberFormatINTERNATIONAL error:&anError]);
        NSLog(@"NATIONAL      : %@", [phoneUtil format:phoneNumberUS numberFormat:NBEPhoneNumberFormatNATIONAL error:&anError]);
        NSLog(@"RFC3966       : %@", [phoneUtil format:phoneNumberUS numberFormat:NBEPhoneNumberFormatRFC3966 error:&anError]);
    }
```

```
INTERNATIONAL : +39 0464 565073
NATIONAL      : 0464 565073
RFC3966       : tel:+39-0464-565073
```

**Comment by iziz** [comment]
If you have another issue, reopen this please.
