### ISSUE TITLE
0.9.1 fails when installing with Carthage: No architectures to compile for (ARCHS=armv7k,...)

### ISSUE THREAD

**Issue by nezhyborets** [iziz/libPhoneNumber-iOS#161]
Here is the log:

> /usr/bin/xcrun xcodebuild -project /Users/oleksiinezhyborets/Projects/Debts/App/Carthage/Checkouts/libPhoneNumber-iOS/libPhoneNumber.xcodeproj -scheme libPhoneNumberwatchOS -configuration Release -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
>     BITCODE_GENERATION_MODE = bitcode
>     CARTHAGE = YES
>     CODE_SIGN_IDENTITY = 
>     CODE_SIGNING_REQUIRED = NO
>     ONLY_ACTIVE_ARCH = NO
>     SDKROOT = watchos3.1
> 
> === CLEAN TARGET libPhoneNumberwatchOS OF PROJECT libPhoneNumber WITH CONFIGURATION Release ===
> 
> Check dependencies
> [BEROR]No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s i386).
> 
> Create product structure
> /bin/mkdir -p /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Products/Release-watchos/libPhoneNumberwatchOS.framework
> /bin/mkdir -p /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Products/Release-watchos/libPhoneNumberwatchOS.framework/Headers
> 
> Clean.Remove clean /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Intermediates/libPhoneNumber.build/Release-watchos/libPhoneNumberwatchOS.build
>     builtin-rm -rf /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Intermediates/libPhoneNumber.build/Release-watchos/libPhoneNumberwatchOS.build
> 
> Clean.Remove clean /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Products/Release-watchos/libPhoneNumberwatchOS.framework
>     builtin-rm -rf /Users/oleksiinezhyborets/Library/Developer/Xcode/DerivedData/libPhoneNumber-gguomwtjuraduvfnbjsdfqtdywds/Build/Products/Release-watchos/libPhoneNumberwatchOS.framework
> 
> ** CLEAN SUCCEEDED **
> 
> === BUILD TARGET libPhoneNumberwatchOS OF PROJECT libPhoneNumber WITH CONFIGURATION Release ===
> 
> Check dependencies
> No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s i386).

**Comment by iziz** [comment]
OK I will add "armv7k" in next version (And would you add "armv7k" to your project for testing ?)
