### ISSUE TITLE
extractPossibleNumber range out of bounds

### ISSUE THREAD

**Issue by Byte2014** [iziz/libPhoneNumber-iOS#164]
The current way to find out second number can find the position before the start.

[`int secondNumberStart = [self stringPositionByRegex:number regex:SECOND_NUMBER_START_PATTERN];`](https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber/NBPhoneNumberUtil.m#L565)

should be replaced with 

`int secondNumberStart = [self stringPositionByRegex:possibleNumber regex:SECOND_NUMBER_START_PATTERN];`

Consider the string "abcdefg\x123"
This will cause out of bound error because substring {0,6} is larger than "123"

**Comment by iziz** [comment]
You are right!
Thanks

**Comment by iziz** [comment]
Updated with 0.9.2
