### ISSUE TITLE
Phone number validation for india is failing

### ISSUE THREAD

**Issue by RMK19** [iziz/libPhoneNumber-iOS#166]
I'm using cocoapod version 0.9.2, validation fails while using isValidNumber for certain numbers which starts like 87788
@iziz

**Comment by DnyaneshwarWagh** [comment]
@iziz for Reference [https://github.com/googlei18n/libphonenumber/issues/1520](https://github.com/googlei18n/libphonenumber/issues/1520)

**Comment by iziz** [comment]
Would you check with 0.9.4 ?

**Comment by RMK19** [comment]
@iziz Thanks it's fixed now.
