### ISSUE TITLE
Unable to use pod version 0.9.3

### ISSUE THREAD

**Issue by RMK19** [iziz/libPhoneNumber-iOS#176]
I'm using pod version 0.9.3 in my project, but while installing pod it shows the following error

**My pod file**
`pod 'libPhoneNumber-iOS', '0.9.3' #ObjC`

**Error in iTerm**
[!] Unable to satisfy the following requirements:

- `libPhoneNumber-iOS (= 0.9.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `libPhoneNumber-iOS (= 0.9.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default. 

The above error prevails even after i updated my repo

**Comment by iziz** [comment]
OK I will fix it tonight

**Comment by RMK19** [comment]
@iziz  I think there is a new update available in [libPhoneNumber](https://github.com/googlei18n/libphonenumber) with new metadata for phone numbers. Please include those also.

**Comment by iziz** [comment]
OK

**Comment by iziz** [comment]
Updated. Thanks

**Comment by RMK19** [comment]
@iziz Thanks for the update. :)
