### ISSUE TITLE
German prefix 152 is invalid

### ISSUE THREAD

**Issue by Hopreeeenjust** [iziz/libPhoneNumber-iOS#179]
Hello.
Seems like +49 152 XXXX XXX phone numbers are defined as not valid by the library.
But in fact these are valid numbers: https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany#Non-geographic_numbering

Can you please fix as some customers complain they could not register their phone number?
Thanks in advance.

**Comment by Hopreeeenjust** [comment]
Any news?

**Comment by dmaclach** [comment]
Do the phone numbers that don't work with the iOS library validate here: 

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by Hopreeeenjust** [comment]
Here is validation log:

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: DE
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: +49 152 864 5559
National format: 1528645559
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

****AsYouTypeFormatter Results****
Char entered: + Output: +
Char entered: 4 Output: +4
Char entered: 9 Output: +49 
Char entered:   Output: +49 
Char entered: 1 Output: +49 1
Char entered: 5 Output: +49 15
Char entered: 2 Output: +49 152
Char entered:   Output: +49 152 
Char entered: 8 Output: +49 152 8
Char entered: 6 Output: +49 152 86
Char entered: 4 Output: +49 152 864
Char entered:   Output: +49 152 864 
Char entered: 5 Output: +49 152 864 5
Char entered: 5 Output: +49 152 864 55
Char entered: 5 Output: +49 152 864 555
Char entered: 9 Output: +49 152 864 5559

**Comment by dmaclach** [comment]
In that case I think you need to file it with the base google library here:

https://github.com/googlei18n/libphonenumber/issues

I took a brief look and didn't see anything similar. Once they fix it there, it will be easy to pick up the change in this library.

**Comment by Hopreeeenjust** [comment]
I created new issue for base phone number library.
Once they report any action i will leave the note in this thread.

Thank you.

**Comment by Hopreeeenjust** [comment]
The issue can be closed.
Thanks for participation.

https://github.com/googlei18n/libphonenumber/issues/1647
