### ISSUE TITLE
Lebanese new phone numbers 

### ISSUE THREAD

**Issue by wassimseif** [iziz/libPhoneNumber-iOS#181]
The new lebanese  phone number that start with 96179******,  96178******, 96182****** , 96183****** will return an invalid phone number while they are valid and recently added

**Comment by dmaclach** [comment]
Do the phone numbers that don't work with the iOS library validate here:

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

If not,  I think you need to file it with the base google library here:

https://github.com/googlei18n/libphonenumber/issues

**Comment by wassimseif** [comment]
![screen shot 2017-03-22 at 4 46 25 pm](https://cloud.githubusercontent.com/assets/7282773/24203705/22360bb2-0f1f-11e7-8c01-6021b823a8fc.png)


```
****Parsing Result:****
{"country_code":961,"national_number":423642,"raw_input":"423642","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): false
Result from isPossibleNumberWithReason(): TOO_SHORT
Note: numbers that are not possible have type UNKNOWN, an unknown region, and are considered invalid.

****Formatting Results:**** 
E164 format: invalid
Original format: 423642
National format: 423642
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid
National format with carrier code: 423642

****AsYouTypeFormatter Results****
Char entered: 4 Output: 4
Char entered: 2 Output: 42
Char entered: 3 Output: 423
Char entered: 6 Output: 4236
Char entered: 4 Output: 42364
Char entered: 2 Output: 423642
```

Is this considered validated ?
