### ISSUE TITLE
Compile error on xcodebuild step after upgrading to 0.9.9

### ISSUE THREAD

**Issue by knishant90** [iziz/libPhoneNumber-iOS#189]
I see this error message when I do xcodebuild with the 0.9.9 version :
`libPhoneNumber-iOS/libPhoneNumber_iOS.framework/Headers/NBGeneratedPhoneNumberMetaData.h:6:10: include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData'`

**Comment by iziz** [comment]
Sorry!
Revert metadata to legacy way (0.9.10)
