### ISSUE TITLE
country name in iOS8 is empty

### ISSUE THREAD

**Issue by baby03201** [iziz/libPhoneNumber-iOS#193]
Hello! 안영 하세요!
Thanks for your great work. 

I am using this awesome library to support international phone number registration.
However, I found out while I list the countries name in iOS 8, it will be empty.

After doing research online, I have fixed it with `[NSLocale systemLocale]` to get default English name if the country name is empty.

Can I send a pull request for this?  Here is my changes
https://github.com/baby03201/libPhoneNumber-iOS/commit/f0adff6f76f11f56da0f849556e732f11ff1926e

**Comment by iziz** [comment]
Sure Thank you (and sorry for late reply)
