### ISSUE TITLE
Wrong destination for Metadata 

### ISSUE THREAD

**Issue by AncAinu** [iziz/libPhoneNumber-iOS#20]
Metadata are currently sent to `NSDocumentDirectory`, this is wrong since files stocked here are sent to iCloud. Even without it, it's wrong since it's not document (word, excel...) but support files used only by the app.

You should use `NSCachesDirectory` (best if the files can be regenerated when missing) or `NSApplicationSupportDirectory` (less subject to discarding when memory is full).

**Comment by iziz** [comment]
Remove plist loading and sharesInstance method.
Try with version 0.8.0 (sorry for late)
