### ISSUE TITLE
Issue with national german number

### ISSUE THREAD

**Issue by lowki93** [iziz/libPhoneNumber-iOS#206]
I try to parse this number : `493030808459`
I have  `+49493030808459`
I should have `+493030808459`

I should have this : 
`http://libphonenumber.appspot.com/phonenumberparser?number=%2B493030808459`

**Comment by beseder42** [comment]
Same here! Experienced same behavior.

**Comment by guillaume-tgl** [comment]
We have experienced the same problem but not sure if this is a bug or an expected behavior. See https://github.com/google/libphonenumber/blob/master/FAQ.md#parsing
