### ISSUE TITLE
Outdated Metadata

### ISSUE THREAD

**Issue by JenssRey** [iziz/libPhoneNumber-iOS#254]
Metadata is out of date. Phone number, 0455142418, is not valid through the iOS library version 0.9.13. 

Output from the online phone number validation:
****Parsing Result:****
{"country_code":32,"national_number":455142418,"raw_input":"0455142418","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: BE
Result from getNumberType(): MOBILE

****ShortNumberInfo Results:****
Result from isPossibleShortNumber: false
Result from isValidShortNumber: false
Result from isPossibleShortNumberForRegion: false
Result from isValidShortNumberForRegion: false

****Formatting Results:**** 
E164 format: +32455142418
Original format: 0455 14 24 18
National format: 0455 14 24 18
International format: +32 455 14 24 18
Out-of-country format from US: 011 32 455 14 24 18
Out-of-country format from Switzerland: 00 32 455 14 24 18

****AsYouTypeFormatter Results****
Char entered: 0 Output: 0
Char entered: 4 Output: 04
Char entered: 5 Output: 045
Char entered: 5 Output: 0455
Char entered: 1 Output: 0455 1
Char entered: 4 Output: 0455 14
Char entered: 2 Output: 0455 14 2
Char entered: 4 Output: 0455 14 24
Char entered: 1 Output: 0455 14 24 1
Char entered: 8 Output: 0455 14 24 18

**Comment by JenssRey** [comment]
Updated Metadata available for review #255

**Comment by LudoLibon** [comment]
HI,
is it possible to generate also the podspec and lib with this new metadata ?
