### ISSUE TITLE
Apple flags binary for Non-public API usage

### ISSUE THREAD

**Issue by dbanik** [iziz/libPhoneNumber-iOS#285]
**Non-public API usage** - The app contains or inherits from non-public classes in <App_NAME>: NBPhoneNumberUtil . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app.

Any fix for this?

**Comment by dmaclach** [comment]
which non-public APIs specifically? and which OS are we testing against?

**Comment by dbanik** [comment]
App-store flagged this for the first build but now the issue has disappeared. Closing this issue.

**Comment by burkaslarry** [comment]
I have still got  this issue for dependency version. 0.9.15

**Comment by burkaslarry** [comment]
I have still got  this issue for dependency version. 0.9.15
