### ISSUE TITLE
iOS 8 issue

### ISSUE THREAD

**Issue by ignotusverum** [iziz/libPhoneNumber-iOS#29]
i'm having next issue: -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL

when i'm trying to input/format phone number in iOS 8

**Comment by vrunoa** [comment]
:+1:  to "sharedInstanceWithBundle:(NSBundle *)bundle"

**Comment by iziz** [comment]
FYI 

Removed all singleton method.
Removed all plist and converted to objective-c source code.
