### ISSUE TITLE
310 phone numbers with only 7 digits are recognized as valid

### ISSUE THREAD

**Issue by nnesiba** [iziz/libPhoneNumber-iOS#30]
310-XXXX phone numbers are found to be valid phone numbers for the state of California. It appears that 310 is actually an area code, and requires an additional 7 digits to be valid. 

There are two locations in the metadata .json/.plist files where regexes to match phone numbers end with "|310\d{4}". 

EDIT: Was not up to date. Closed.

**Comment by allbto** [comment]
I actually have the same issue.
(+1) 310-XXXX numbers are found to be valid. But 310 phone numbers require 7 digit after the area code like the rest of the US based phone numbers.

The pattern ("|310\\d{4}") now appears in the `NBPhoneMetadataCA` class.

**Comment by snowmen10** [comment]
Hi @iziz 

I also have the same issue, and it is the same as @allbto  described.
