### ISSUE TITLE
Result is different from Google and iOS Library

### ISSUE THREAD

**Issue by duy-dindinn** [iziz/libPhoneNumber-iOS#324]
Hello,

I am using version 1.0.2 and one of my phone number does not return the same result as Google demo site.
The phone number is +65 8921 xxxx.

From iOS library:
```
- (NBEPhoneNumberType)getNumberType:(NBPhoneNumber *)phoneNumber;
```
returns UNKNOWN

```
- (BOOL)isValidNumberForRegion:(NBPhoneNumber *)number regionCode:(NSString *)regionCode;
```
return false

From Google:
```
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: SG
Result from getNumberType(): MOBILE
```

What should I do to get the correct result?
Thanks in advance!

Regards,
Duy

**Comment by duy-dindinn** [comment]
Fixed by using NBPhoneNumberUtil.sharedInstance instead of NBPhoneNumber()

**Comment by simonmitchell** [comment]
Ohh my god @duy-dindinn you saved me!!
