### ISSUE TITLE
Push new version 1.0.3

### ISSUE THREAD

**Issue by alexey1312** [iziz/libPhoneNumber-iOS#329]
Hi!
Please realise new version,  really need the [Fix 'umbrella header for module does not include...' error](https://github.com/iziz/libPhoneNumber-iOS/commit/4377b21c870e9b41ca10b4798f5252d2accd571a) 
Thx!

**Comment by olejnjak** [comment]
Please before addressing this, check #331 as I think that merging #326 just made the header import reappear

**Comment by rockebee** [comment]
I have added PR #340 to the 1.0.3 release wishlist and created PR #341 for actual version bump.
