### ISSUE TITLE
NBAsYouTypeFormatter doesn't work

### ISSUE THREAD

**Issue by x2on** [iziz/libPhoneNumber-iOS#36]
If i init a `NBAsYouTypeFormatter` it doesn't work.

I think it's because it calls `loadMetadata:` in `NBPhoneNumberUtil` and the unarchive doesn't work:

`unarchiveData = [NSKeyedUnarchiver unarchiveObjectWithData:fileData];` in line 499 returns `nil`.

Any idea why this happens?

**Comment by iziz** [comment]
Remove plist loading and sharesInstance method.
Try with version 0.8.0 (sorry for late)
