### ISSUE TITLE
AsYouTypeFormatter for international phone numbers

### ISSUE THREAD

**Issue by amitai-hoze** [iziz/libPhoneNumber-iOS#38]
Hi, I'm using version 0.7.5, and I need an AsYouTypeFormatter for international numbers. The one in libPhoneNumber-iOS requires a `defaultRegion`, I tried entering `nil` but got an `INVALID_COUNTRY_CODE` error.

I thought of implementing it on my own using the existing functions in libPhoneNumber-iOS, but couldn't find enough documentation on `NBPhoneNumberUtil`'s functions. I basically need to parse an international number (e.g. 16314032031) and format it (e.g. "+1 (631) 403-2031"), and the rest I can implement on my own. can you tell me how to do it?

Thanks, Amitai.

**Comment by amitai-hoze** [comment]
OK, I managed to find out how to do it, here is what I did if anyone else is interested.
`formattedPhoneNumberSubstring` takes a partial phone number string and formats it as the beginning of a properly formatted international number, e.g. "16463" turns to "+1 646-3".
```objective-c
NSString *formattedPhoneNumberSubstring(NSString *phoneNumber) {
    NBPhoneNumberUtil *phoneUtil = [NBPhoneNumberUtil sharedInstance];
    phoneNumber = [phoneUtil normalizeDigitsOnly:phoneNumber];
    NSString *nationalNumber;
    NSNumber *countryCode = [phoneUtil extractCountryCode:phoneNumber nationalNumber:&nationalNumber];
    if ([countryCode isEqualToNumber:@0])
        return phoneNumber;
    
    NSString *regionCode = [[phoneUtil regionCodeFromCountryCode:countryCode] objectAtIndex:0];
    NSString *paddedNationalNumber = [nationalNumber stringByPaddingToLength:15 withString:@"0" startingAtIndex:0];
    NSString *formatted;
    NSString *formattedSubstr;
    for (int i=0; i < paddedNationalNumber.length; i++) {
        NSError *error = nil;
        formattedSubstr = [phoneUtil format:[phoneUtil parse:[paddedNationalNumber substringToIndex:i] defaultRegion:regionCode error:&error]
                               numberFormat:NBEPhoneNumberFormatINTERNATIONAL error:&error];
        if (getExtraCharacters(formattedSubstr) > getExtraCharacters(formatted)) // extra characters means more formatted
            formatted = formattedSubstr;
    }
    
    // Preparing the buffer for phoneNumber
    unichar phoneNumberBuffer[phoneNumber.length+1];
    [phoneNumber getCharacters:phoneNumberBuffer range:NSMakeRange(0, phoneNumber.length)];
    
    // Preparing the buffer for formatted
    unichar formattedBuffer[formatted.length+1];
    [formatted getCharacters:formattedBuffer range:NSMakeRange(0, formatted.length)];
    
    int j=0;
    for(int i = 0; i < phoneNumber.length && j < formatted.length; i++) {
        while(formattedBuffer[j] != phoneNumberBuffer[i]) j++;
        j++;
    }
    
    return [formatted substringToIndex:j];
}
```

Also, if anyone's interested in ReactiveCocoa, here's how to do bind it to a UITextField:
```objective-c
RAC(self,phoneNumberTextField.text) =
[[self.phoneNumberTextField.rac_textSignal
  map:^NSString*(NSString *phoneNumber) {
      return formattedPhoneNumberSubstring(phoneNumber);
  }] deliverOn:[RACScheduler mainThreadScheduler]];
```

**Comment by iziz** [comment]
Sorry for late reply.
Phone number has various formatting rule for each country. Because, You must enter specific country code for formatting phone number. (International or not)

But, if you can't recognize the country code for some phone number.
Your solution will be helpful.

And, if you want to add that features to "libPhoneNumber-iOS".
Just create "pull request". :)
Thanks.
