### ISSUE TITLE
Access to the support regions

### ISSUE THREAD

**Issue by RedBlueThing** [iziz/libPhoneNumber-iOS#41]
Would be great to have access to the regions supported by the library. So something like this in NBPhoneNumberUtil.m.

    - (NSArray*)supportedRegions
    {
        return [[_mapCCode2CN allKeys] sortedArrayUsingComparator:^(NSString* lhs, NSString* rhs){
            NSString* lhsCountry = [[NSLocale currentLocale] displayNameForKey: NSLocaleCountryCode value:lhs];
            NSString* rhsCountry = [[NSLocale currentLocale] displayNameForKey: NSLocaleCountryCode value:rhs];
            return [lhsCountry compare:rhsCountry];
        }];
    }

**Comment by iziz** [comment]
Good, Just create pull request.

**Comment by iziz** [comment]
https://github.com/iziz/libPhoneNumber-iOS/pull/77
