### ISSUE TITLE
NBAsYouTypeFormatter: Lacks support for handling changes to the middle of a phone number string

### ISSUE THREAD

**Issue by dtrenz** [iziz/libPhoneNumber-iOS#43]
If I use the NBAsYouTypeFormatter to format text as it is typed into a UITextField via textField:shouldChangeCharactersInRange:replacementString: there doesn't appear to be any methods that support changing digits in the middle of a phone number string, only support for adding or removing digits from the tail.

Something like:
```obj-c
- (NSString *)inputDigit:(NSString *)nextChar atPosition:(NSUInteger)position;
```

**Comment by iziz** [comment]
How about to use below method ?

- (NSString *)inputString:(NSString *)string;
- (NSString *)inputStringAndRememberPosition:(NSString *)string;

**Comment by dtrenz** [comment]
Will that work? How would I use that method to achieve this? I'm not sure I fully understand how inputStringAndRememberPosition: is intended to be used.

**Comment by iziz** [comment]
Just input whole string.

[asFormatter inputString:@"123412"];

**Comment by dtrenz** [comment]
I'll try that. Thanks

**Comment by iziz** [comment]
OK~, tell me if you have any issue.
