### ISSUE TITLE
Unclear method names for country/region codes

### ISSUE THREAD

**Issue by blixt** [iziz/libPhoneNumber-iOS#44]
The API appears to be intermixing the terms "country code" and "region code", which is really confusing. See the example below:

```obj-c
NBPhoneNumberUtil *util = [NBPhoneNumberUtil sharedInstance];

// This returns a "country code" and will in this case give something like "US".
NSString *country = [[util countryCodeByCarrier] uppercaseString];

// These two methods expect "region codes", which in this case is something like "US".
self.asYouTypeFormatter = [[NBAsYouTypeFormatter alloc] initWithRegionCode:countryCode];
NSString *prefix = [util countryCodeFromRegionCode:countryCode];

// This will take a "country code" and return a "region code". In this case it takes the number 46 and returns the string "SE".
[util regionCodeFromCountryCode:@46];
```

**Comment by iziz** [comment]
Yep, me too and totally agreed.
(It comes from libphonenumber's source code method naming.)

So, What will be best ?
in http://countrycode.org/

// Country Codes, Phone Codes, Dialing Codes, Telephone Codes, ISO Country Codes

1. Country code -> ISO Code or National Code ?
2. Country calling code -> Country Calling Code ?
3. Region calling code -> Region Calling Code ?

Tell me your suggestion. :)

**Comment by iziz** [comment]
Any idea ?
