### ISSUE TITLE
concurrency issue

### ISSUE THREAD

**Issue by ferreol** [iziz/libPhoneNumber-iOS#51]
Hi
I am using latest source from this repository.

I am still facing concurrency issues than https://github.com/me2day/libPhoneNumber-iOS/issues/39
Using multiple threads using different instances of nbphonenumberutil
Any test I could do to help solve ?

regards

ferreol

**Comment by iziz** [comment]
Please test with latest commit.
I was removed static methods (metadata) temporarily.
And tell me your result.

**Comment by iziz** [comment]
I will release 0.8.4 if it has no issue. (waiting your result)

**Comment by ferreol** [comment]
Hi iziz, 
thank you so much for your quick fix.
So far this has fixed the issue that I had noticed at launch time (while loading contacts phone numbers).

Let's consider it fixed, I would re comment if after some more extensive testing it reappers.
