### ISSUE TITLE
SIGABRT in 0.8.3

### ISSUE THREAD

**Issue by johnryan** [iziz/libPhoneNumber-iOS#52]
Got a sigabrt after updating to the latest cocoapod. Not sure if this is something wrong on my end, but I'm just calling parse using the (now deprecated) singleton number formatter

Thread : Crashed: com.apple.root.default-priority
0  libsystem_kernel.dylib         0x0000000191b2658c __pthread_kill + 8
1  libsystem_pthread.dylib        0x0000000191ba916c pthread_kill + 104
2  libsystem_c.dylib              0x0000000191aba808 abort + 112
3  libsystem_malloc.dylib         0x0000000191b605c4 _nano_malloc_check_clear
4  libsystem_malloc.dylib         0x0000000191b5f548 nano_free + 252
5  CoreFoundation                 0x0000000184f02ad8 __CFStringDeallocate + 192
6  CoreFoundation                 0x0000000184e29f8c CFRelease + 316
7  App                          0x000000010058ce64 +[NBMetadataHelper getMetadataForRegion:] (NBMetadataHelper.m:228)
8  App                          0x0000000100598b94 -[NBPhoneNumberUtil isValidRegionCode:] (NBPhoneNumberUtil.m:993)
9  App                          0x00000001005a4830 -[NBPhoneNumberUtil checkRegionForParsing:defaultRegion:] (NBPhoneNumberUtil.m:3235)
10 App                          0x00000001005a54a0 -[NBPhoneNumberUtil parseHelper:defaultRegion:keepRawInput:checkRegion:error:] (NBPhoneNumberUtil.m:3414)
11 App                          0x00000001005a4998 -[NBPhoneNumberUtil parse:defaultRegion:error:] (NBPhoneNumberUtil.m:3265)

**Comment by iziz** [comment]
Please test with latest commit.
I was removed static methods (metadata) temporarily.
And tell me your result.

**Comment by iziz** [comment]
I will release 0.8.4 if it has no issue. (waiting your result)

**Comment by johnryan** [comment]
I'm not able to reproduce the crash with the latest commit, so looks good. Thanks for the quick response!
