### ISSUE TITLE
Random SIGABORT

### ISSUE THREAD

**Issue by arturogutierrez** [iziz/libPhoneNumber-iOS#53]
I've suffering random crashes in the lib when I try to parse a lot of numbers from different numbers, but I can't get a piece of code where I can reproduce it manually. I have the stack trace here:

https://www.dropbox.com/s/0kvi9kgpgxv9w06/Screenshot%202015-03-11%2018.28.56.png?dl=0

Can you took a look and help me to try to get a fix?

Thanks in advance

**Comment by iziz** [comment]
Use latest code from https://github.com/iziz/libPhoneNumber-iOS (without cocoapods).

And tell me its result.

(I will update new version to cocoapods, if it works fine.)

**Comment by iziz** [comment]
Please give me some feedback :)

**Comment by arturogutierrez** [comment]
I'll try today and I'll tell you the results.

**Comment by arturogutierrez** [comment]
I think it works, I haven't received more crashes up to now so feel free to release a new version to cocoapods.
Thanks for your help!
