### ISSUE TITLE
parseWithPhoneCarrierRegion not working

### ISSUE THREAD

**Issue by wojciechczyz** [iziz/libPhoneNumber-iOS#55]
parseWithPhoneCarrierRegion fails when phone number is missing country code - in this case when testing with spanish provider, es, which should translat to +34, but still fails with:

"Error Domain=INVALID_COUNTRY_CODE Code=0 "INVALID_COUNTRY_CODE:es" UserInfo=0x17426be40 {NSLocalizedDescription=INVALID_COUNTRY_CODE:es}" UserInfo=0x17007e800 {NSLocalizedDescription=Error Domain=INVALID_COUNTRY_CODE Code=0 "INVALID_COUNTRY_CODE:es" UserInfo=0x17426be40 {NSLocalizedDescription=INVALID_COUNTRY_CODE:es}}

**Comment by iziz** [comment]
Please show me your code sample.

**Comment by wojciechczyz** [comment]
Hi,

I am using this method and calling it providing non country marked number for example:
“123 123 123”

+(NSString *)NormalizePhoneNumber : (NSString *)AnyPhoneNumber
{
    NSString *NormalizedPhoneNumber;
    @try
    {
        NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
        NSError *anError = nil;
        NBPhoneNumber *myNumber = [phoneUtil parseWithPhoneCarrierRegion:AnyPhoneNumber error:&anError];
        if (anError == nil)
        {
            NormalizedPhoneNumber = [phoneUtil format:myNumber numberFormat:NBEPhoneNumberFormatE164 error:&anError];
            if (anError == nil)
            {
                NSLog(@"E164 normalized: %@", NormalizedPhoneNumber);
                
            }
            else
            {
                NSLog(@"Failed normalizing: %@, Error: %@", AnyPhoneNumber, anError);
                [phoneUtil normalizePhoneNumber : AnyPhoneNumber];
            }
        }
        else
        {
            NSLog(@"Failed parsing: %@, Error: %@", AnyPhoneNumber, anError);
            NormalizedPhoneNumber = [phoneUtil normalizePhoneNumber : AnyPhoneNumber];
        }
    }
    @catch (NSException *CatchedException)
    {
        NSLog(@"Failed parsing and normalizing phone:%@, Error:%@", AnyPhoneNumber, CatchedException.description);
        NormalizedPhoneNumber = AnyPhoneNumber;
    }

    return NormalizedPhoneNumber;
}

I can see that internally “es” is detected but it fails to convert it to +34.
Thanks,
Wojciech

**Comment by iziz** [comment]
"parseWithPhoneCarrierRegion" will works only real device because accessing device sim card. 

In simulator... (defaultRegion "ZZ" -> "US")

```
NSLog(@"%@", [AppDelegate NormalizePhoneNumber:@"123 123 123"]);
```

shows

```
2015-03-18 15:43:13.690 PhoneNumberDevelopment[10350:264935] E164 normalized: +123123123
2015-03-18 15:43:13.691 PhoneNumberDevelopment[10350:264935] +123123123
```

but, can't find that error.

I tried 
```
    NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
    NSError *error = nil;
    
    NBPhoneNumber *phoneNumber = [phoneUtil parse:@"123 123 123" defaultRegion:@"ES" error:&error];
    if (!error) {
        NSLog(@"%@", [phoneUtil format:phoneNumber numberFormat:NBEPhoneNumberFormatE164 error:&error]);
    }
```

and it's result

```
2015-03-18 15:48:12.079 PhoneNumberDevelopment[10443:268516] +34123123123
```

So, tell me your expected result.
