### ISSUE TITLE
In some case the parse cause the crash

### ISSUE THREAD

**Issue by t3573393** [iziz/libPhoneNumber-iOS#57]
0   libsystem_c.dylib             	0x36b93769 usleep$NOCANCEL + 1
		1   libsystem_c.dylib             	0x36bad90d abort + 81
		2   libsystem_malloc.dylib        	0x36c3e3ab szone_error + 331
		3   libsystem_malloc.dylib        	0x36c3e655 free_list_checksum_botch + 25
		4   libsystem_malloc.dylib        	0x36c363ff tiny_malloc_from_free_list + 1023
		5   libsystem_malloc.dylib        	0x36c34eb7 szone_malloc_should_clear + 219
		6   libsystem_malloc.dylib        	0x36c34da7 malloc_zone_malloc + 87
		7   CoreFoundation                	0x28b281c9 __CFStringChangeSizeMultiple + 777
		8   CoreFoundation                	0x28a877a9 CFStringCreateMutableCopy + 409
		9   CoreFoundation                	0x28a9ee87 -[__NSCFString mutableCopyWithZone:] + 23
		10  Foundation 0x2979b811 -[NSString stringByReplacingOccurrencesOfString:withString:options:range:] + 145
		11  Foundation 0x2979b779 -[NSString stringByReplacingOccurrencesOfString:withString:] + 57
		12  Lion 0x005f5c6d +[NBPhoneNumberUtil normalizeNonBreakingSpace:] (NBPhoneNumberUtil.m:172)
		13  Lion 0x005fa0cb -[NBPhoneNumberUtil isViablePhoneNumber:] (NBPhoneNumberUtil.m:780)
		14  Lion 0x00601ba3 -[NBPhoneNumberUtil parseHelper:defaultRegion:keepRawInput:checkRegion:error:] (NBPhoneNumberUtil.m:3667)
		15  Lion 0x006019f9 -[NBPhoneNumberUtil parseAndKeepRawInput:defaultRegion:error:] (NBPhoneNumberUtil.m:3619)

I think the method -[NBPhoneNumberUtil buildNationalNumberForParsing: nationalNumber:] , cause this result, Had better use the NSMutableString to deal with case .

**Comment by iziz** [comment]
Could you update your libPhoneNumber-iOS to latest version ?
There is no "static normalizeNonBreakingSpace method" in NBPhoneNumberUtil :)

**Comment by Omarj** [comment]
@iziz  :+1:
