### ISSUE TITLE
I can't validate pakistani numbers

### ISSUE THREAD

**Issue by SonGoku68** [iziz/libPhoneNumber-iOS#58]
I'm trying to validate pakistani numbers but I'm "false" when I check if my phone number is valid.

The number I'm trying to check is: +923406171134. I also tested it in http://libphonenumber.appspot.com and I'm getting "valid" as result:

Phone Number entered: +923406171134
defaultCountry entered: GB
Language entered: en
Parsing Result
country_code	92
national_number	3406171134
extension	 
country_code_source	FROM_NUMBER_WITH_PLUS_SIGN
italian_leading_zero	false
raw_input	+923406171134
Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	true
Result from isValidNumberForRegion()	false
Phone Number region	PK
Result from getNumberType()	MOBILE
Formatting Results
E164 format	+923406171134
Original format	+92 340 6171134
National format	0340 6171134
International format	+92 340 6171134
Out-of-country format from US	011 92 340 6171134
Out-of-country format from CH	00 92 340 6171134
AsYouTypeFormatter Results
Char entered: '+' Output:	+
Char entered: '9' Output:	+9
Char entered: '2' Output:	+92
Char entered: '3' Output:	+92 3
Char entered: '4' Output:	+92 34
Char entered: '0' Output:	+92 340
Char entered: '6' Output:	+92 340 6
Char entered: '1' Output:	+92 340 61
Char entered: '7' Output:	+92 340 617
Char entered: '1' Output:	+92 340 6171
Char entered: '1' Output:	+92 340 61711
Char entered: '3' Output:	+92 340 617113
Char entered: '4' Output:	+92 340 6171134
PhoneNumberOfflineGeocoder Results
Location	Pakistan
PhoneNumberToTimeZonesMapper Results
Time zone(s)	[Asia/Karachi]
PhoneNumberToCarrierMapper Results
Carrier	Telenor

**Comment by mrojas** [comment]
Having the same issue here with a number starting with "+92340" (Telenor Pakistan)

**Comment by iziz** [comment]
I will check code & metadata.

**Comment by iziz** [comment]
```
        NSError *error = nil;
        NBPhoneNumber *phoneNumberUS = [phoneUtil parse:@"+923406171134" defaultRegion:@"GB" error:&error];
        if (error) {
            NSLog(@"err [%@]", [error localizedDescription]);
        }
        NSLog(@"- isValidNumber [%@]", [phoneUtil isValidNumber:phoneNumberUS] ? @"YES" : @"NO");
        NSLog(@"- isPossibleNumber [%@]", [phoneUtil isPossibleNumber:phoneNumberUS error:&error] ? @"YES" : @"NO");
        NSLog(@"- getRegionCodeForNumber [%@]", [phoneUtil getRegionCodeForNumber:phoneNumberUS]);
```

shows

```
2015-04-05 21:34:26.700 libPhoneNumber[17860:5079591] - - - - - GB / +923406171134
2015-04-05 21:34:26.702 libPhoneNumber[17860:5079591] - isValidNumber [YES]
2015-04-05 21:34:26.702 libPhoneNumber[17860:5079591] - isPossibleNumber [YES]
2015-04-05 21:34:26.702 libPhoneNumber[17860:5079591] - getRegionCodeForNumber [PK]
```

I think it works fine... any issues ?
