### ISSUE TITLE
finnish phone number don't get recognised

### ISSUE THREAD

**Issue by frranck** [iziz/libPhoneNumber-iOS#59]
Hello,

Finnish phones numbers don't get recognised:

    NSString *nationalNumber = nil;
    NSNumber *countryCode = [phoneUtil extractCountryCode:@"+358401493292" nationalNumber:&nationalNumber];

countryCode returns 0.

**Comment by iziz** [comment]
countryCode  = 358
nationalNumber = 401493292

is right ?

**Comment by iziz** [comment]
Maybe that issue causes with '+' character.
So I added some exception code. Check latest update code from github.b.

**Comment by frranck** [comment]
countryCode = 358
nationalNumber = 0401493292
Note that i had no problem with other country codes like france +33

**Comment by iziz** [comment]
Did you checked with latest code ?

**Comment by frranck** [comment]
Thanks yes, that fixed the problem.
