### ISSUE TITLE
Why the phone number format pattern is different for the same country on different devices (android and iOS) using libphonenumber library?

### ISSUE THREAD

**Issue by modibhaviks** [iziz/libPhoneNumber-iOS#61]
I have used the same library for iOS and Android with same method/code for formatting phone number

For example the format of same Indian mobile number without country code for iOS is different from android SDK

Android SDK:    XX XX XXXXXX
iOS SDK:        XXXXX XXXXX
While formatting of US phone number using same library in iOS and Android gives similar output but for Indian mobile number the output varies.

http://stackoverflow.com/questions/29773301/why-the-phone-number-format-pattern-is-different-for-the-same-country-on-differe

**Comment by iziz** [comment]
Could you show me your example code ?

**Comment by modibhaviks** [comment]
NBPhoneNumberUtil *phoneUtilObj = [[NBPhoneNumberUtil alloc] init];
NBAsYouTypeFormatter *asYouTypeFormatter = [[NBAsYouTypeFormatter alloc] initWithRegionCode:@"IN"];
NBPhoneNumber *phoneNumber = [phoneUtilObj parseAndKeepRawInput:@"XXXXXXXXXX" defaultRegion:@"IN" error:&anError];
NSString *formattedNumber = [phoneUtilObj format:phoneNumber numberFormat:NBEPhoneNumberFormatINTERNATIONAL error:&anError];

**Comment by iziz** [comment]
Maybe you don't need to use
```
NBAsYouTypeFormatter *asYouTypeFormatter = [[NBAsYouTypeFormatter alloc] initWithRegionCode:@"IN"];
```

And please tell me some sample number.
