### ISSUE TITLE
The "countryCodeFromRegionCode" method of "BMetadataHelper", returns "nil" for some region codes.

### ISSUE THREAD

**Issue by Hordaric** [iziz/libPhoneNumber-iOS#64]
For AQ, BV, GS, HM, PN, TF, UM region codes "countryCodeFromRegionCode" method returns nil.

**Comment by iziz** [comment]
Yes, it does not exists in google's libphonenumber metadata too.
see https://github.com/googlei18n/libphonenumber

**Comment by Hordaric** [comment]
Sorry for confusion.

**Comment by iziz** [comment]
No problem :)
