### ISSUE TITLE
Separate and Remove Depencies from Implementation Code on Test Code

### ISSUE THREAD

**Issue by chrisjf** [iziz/libPhoneNumber-iOS#66]
Hello! Thank you for the project. In our project we don't use CocoaPods, thus Framework support is necessary for us. It would be great to have this, or a static library.

Also, I tried to import the project and there seems to be unnecessary imports e.g. NBMetadataCoreTest.h. Why are the tests included in the actual code? It would be better if the tests were separated from the actual code.

If these improvements pique your interest I would be open to creating and submitting a pull request for you. :) Thanks in advance for your feedback.

**Comment by iziz** [comment]
Thanks your feedback.
I'll clean up unnecessary imports.

And, why you need framework or static library ?
(You don't want adding source code in your project ?)

**Comment by chrisjf** [comment]
Thank you for the quick reply! As for Framework support, it would be a "nice to have" but it's not 100% necessary. And that sounds great about the imports and separating the test code from the actual code. I have changed the title of the issue to reflect the future changes. If you have any questions let me know. :)

**Comment by iziz** [comment]
see latest commit (a3c85e2)
and feel free to 'create pull request' if you have any good idea.

ps, It works fine...  but I'm not satisfy with using pre-define syntax.

thanks :)

**Comment by chrisjf** [comment]
Wow that was quick! Yes, I agree with you that using #if macros is not the best solution. But thank you for the fix all the same.
