### ISSUE TITLE
isViablePhoneNumber returns true for number that cannot be parsed

### ISSUE THREAD

**Issue by larsekman** [iziz/libPhoneNumber-iOS#67]
I am parsing the numbers in the user's contact list, and the following number causes the parse function to crash:

"927636539 nytt- (old)533021236"

In order to prevent crashes like this, I run isViablePhoneNumber on every number before attempting a parse. This works for many "numbers" that are in fact things like user account names or other text strings, but for the above number, it does return true, even though supplying that number to the parse function causes it to crash.

**Comment by iziz** [comment]
Would you show me your usage code block ?

**Comment by iziz** [comment]
And, see below my sample test code.

```
    // isViablePhoneNumber returns true for number that cannot be parsed #67
    // https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
    NSString *countryCode = @"EN";
    NSString *testNumber = @"927636539 nytt- (old)533021236";
    BOOL isViableTestNumber = [phoneUtil isViablePhoneNumber:testNumber];
    BOOL isValidTestNumber = [phoneUtil isViablePhoneNumber:testNumber];

    NSLog(@"isValidTestNumber [%@]", isValidTestNumber ? @"YES":@"NO");
    NSLog(@"isViableTestNumber [%@]", isViableTestNumber ? @"YES":@"NO");
    
    NBPhoneNumber *parsedTestNumber = [phoneUtil parse:testNumber defaultRegion:countryCode error:&anError];
    if (anError) {
        NSLog(@"error : %@", anError.localizedDescription);
    } else {
        BOOL isValidNumber = [phoneUtil isValidNumberForRegion:parsedTestNumber regionCode:countryCode];
        NSLog(@"isValidNumber [%@]", isValidNumber ? @"YES":@"NO");
        
        NSError *parseError = nil;
        NSLog(@"%@", [phoneUtil format:parsedTestNumber numberFormat:NBEPhoneNumberFormatE164 error:&parseError]);
    }
```

**Comment by larsekman** [comment]
I will try this now and get back to you.

**Comment by larsekman** [comment]
I am using Swift. Here is the code I used for my test case, and it returns true:

```
        var phoneUtil: NBPhoneNumberUtil = NBPhoneNumberUtil.sharedInstance()
        return phoneUtil.isViablePhoneNumber("927636539 nytt- (old)533021236"))

```

**Comment by iziz** [comment]
"isViablePhoneNumber" method only check "phone number" format in whole country.
You should check with your "countryCode" (ex "US", "CH")

**Comment by larsekman** [comment]
But the problem is that if I run `phoneUtil.parse(number, defaultRegion: isoCode, error: &error)`, with the country code, the function crashes with `unexpectedly found nil while unwrapping an Optional value`. I can't check the status of the error object modified by the `parse` function (the `anError` variable in your example), because the app has already crashed by then.

I am perfectly fine with skipping those numbers that are in the wrong format, or those that can't be parsed, but in order to do that I need some way of knowing that before `parse` crashes with `unexpectedly found nil while unwrapping an Optional value`.

In any case, I think it's strange that `"927636539 nytt- (old)533021236"` would be considered a viable phone number for any region. Or are there in fact regions where it is fine to have letters in the middle of the number?

**Comment by iziz** [comment]
OK, I see.
Please show me your code. I will check with swift.

**Comment by iziz** [comment]
https://github.com/iziz/libPhoneNumber-iOS/issues/21
FYI

**Comment by iziz** [comment]
Still not solved ?
