### ISSUE TITLE
Line will never be executed issue

### ISSUE THREAD

**Issue by avielg** [iziz/libPhoneNumber-iOS#68]
Xcode has pointed me with a compile warning to a line that can never be executed:
````
//  NBAsYouTypeFormatter.m

- (NSString*)attemptToChooseFormattingPattern_
.
.
return [self maybeCreateNewTemplate_] ? [self inputAccruedNationalNumber_] : self.accruedInput_;
````
This is at line 1000

**Comment by iziz** [comment]
Could you show me your error code ?
And I like to see your usage.

**Comment by avielg** [comment]
This is how it looks, on Xcode 6.3.1 (They made the compiler warnings a lot more pedant in this version)
![screen shot 2015-05-14 at 18 18 50](https://cloud.githubusercontent.com/assets/5012557/7634772/bda0c6f8-fa65-11e4-9857-1c0d8f4bfa71.png)

**Comment by iziz** [comment]
I was update from
https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/asyoutypeformatter.js

See, latest commit. Thank you very much.
