### ISSUE TITLE
Changing classes names

### ISSUE THREAD

**Issue by vrunoa** [iziz/libPhoneNumber-iOS#69]
Hi @iziz, i'm trying to include ```libPhoneNumber``` inside a framework i'm helping to build. To avoid crashes, when another app is using this framework and also includes your library, i'm changing the class names by adding a prefix. The problem is that when I change the classes names the library is not formatting anymore. Have any clue why ?

**Comment by iziz** [comment]
If you don't mind, Can I see that codes ?

**Comment by vrunoa** [comment]
I manage to make it work using the latest version of the library. I just have one test failing ```(testAustriaNationalNumberParsing)``` 

Here's the source: 
[https://github.com/Urucas/libPhoneNumber-iOS](https://github.com/Urucas/libPhoneNumber-iOS)

**Comment by iziz** [comment]
Sorry for late.

"testAustriaNationalNumberParsing" tets will always fail. (you can ignore this, and it is not exist in latest code)

But, maybe I think it need to update for some warning "PreferredDomesticCarrierCode" -> "preferredDomesticCarrierCode".

**Comment by vrunoa** [comment]
Thanks for your feedback @iziz . I'll left the ```testAustriaNationalNumberParsing``` failing, and change ```PreferredDomesticCarrierCode``` -> ```preferredDomesticCarrierCode```.

**Comment by iziz** [comment]
So, it works fine ?

**Comment by vrunoa** [comment]
It's working fine.

**Comment by iziz** [comment]
OK  good, thanks :)
