### ISSUE TITLE
isValidNumber is failing some valid numbers.

### ISSUE THREAD

**Issue by jrapoport** [iziz/libPhoneNumber-iOS#7]
"(366) 522-8999" parsed with "US" and "+84 74 883313" parsed with "ZZ" both fail isValidNumber:

Changing the area code to something like "(818) 522-8999" for the first one passes.

 "+84 74 883313" is a valid number for Vietnam - from wikipedia:
Area codes starting with 7[edit]
With effect from 5 October 2008, all telephone numbers in this area have 7 digits.
74 – Trà Vinh Province
http://en.wikipedia.org/wiki/Telephone_numbers_in_Vietnam

Debugging a little it looks like the problem is somewhere in this returning nil
 NSString *regionCode = [self getRegionCodeForNumber:number];

I'm guessing this has something to do with metadata rules?

**Comment by anton-matosov** [comment]
According to this site http://www.computerhope.com/areacode.htm

366, 367, and 368 are unassigned area codes

So it looks like expected validation result

**Comment by TechbirdsYogendra** [comment]
I have saved number "6375273023" in my Contacts. When I validate number it returns false. Can anyone help.

NBPhoneNumberUtil *phoneUtil = [NBPhoneNumberUtil sharedInstance];
    NSError *anError = nil;

  NBPhoneNumber *myNumber = [phoneUtil parse:mobileNumber
                                 defaultRegion:@"IN" error:&anError];

BOOL isValidNumber = [phoneUtil isValidNumber:myNumber];

isValidNumber returns NO.

Can anyone help.
