### ISSUE TITLE
what is the correct import statement for bridging header in swift project using cocoapods

### ISSUE THREAD

**Issue by mypark** [iziz/libPhoneNumber-iOS#70]
I'm trying to use libPhoneNumber-iOS/NBPhoneNumber in a swift project and I'm getting a file not found error in the bridging header.

I'm using this import statement in the bridging header file

`#import <libPhoneNumber-iOS/NBPhoneNumber.h>`

Should I be using a different import statement?

**Comment by iziz** [comment]
Are you using cocoapods or added it manually ?

**Comment by mypark** [comment]
using cocopods 

https://www.dropbox.com/s/nfqtldna1lrg1iv/Screenshot%202015-05-30%2008.36.15.png?dl=0

**Comment by mypark** [comment]
so I think I figured out the problem: the "-" in the path gets replace with an underscore automatically by cocoapods.  Thus it should be 

#import <libPhoneNumber_iOS/NBPhoneNumber.h> 

Perhaps it might be good to add that to the readme for a swift cocoapods example?

**Comment by iziz** [comment]
OK I will add in readme soon.

**Comment by mypark** [comment]
so about the issue I'm still having - I should just be able to use the import statement as noted above - what am I missing?

**Comment by iziz** [comment]
You don't need import it in swift, just use it.
And, swift guide was updated it in README.

**Comment by mypark** [comment]
I think the readme might be wrong if using cocoapods

#import "libPhoneNumber-iOS/NBPhoneNumberUtil.h"
#import "libPhoneNumber-iOS/NBPhoneNumber.h"

didnt work for me

this import statement below did work for me
#import <libPhoneNumber_iOS/NBPhoneNumberUtil.h>
#import <libPhoneNumber_iOS/NBPhoneNumber.h>

**Comment by iziz** [comment]
In may case it didn't changed ("-" to "_").
Anyway, you can see your library path in project navigator view.
