### ISSUE TITLE
Crash when using from multiple threads

### ISSUE THREAD

**Issue by futuretap** [iziz/libPhoneNumber-iOS#71]
I'm using libPhoneNumber (installed version 0.8.5 from CocoaPods) from multiple threads. Each thread creates its own instance of `NBPhoneNumberUtil`. Now I'm seeing a rare crash where one thread is in the middle of a `NBPhoneNumberUtil` operation. The other has just finished it and is crashing in the release/teardown of `NBPhoneNumberUtil`. At least that's how it looks like.

This is my thread with the `NBPhoneNumberUtil` operation in progress:

	0   libsystem_platform.dylib             0x00000001947092f8 _platform_memmove + 168
	1   libicucore.A.dylib                   0x00000001939094c4 utext_openCharacterIterator + 2644
	2   libicucore.A.dylib                   0x0000000193908f9c utext_openCharacterIterator + 1324
	3   libicucore.A.dylib                   0x00000001939084e8 utext_clone + 28
	4   libicucore.A.dylib                   0x00000001939bcba4 icu::RegexMatcher::reset(UText*) + 60
	5   libicucore.A.dylib                   0x00000001939fd6e8 uregex_setText + 196
	6   Foundation                           0x00000001835323e0 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 1884
	7   Foundation                           0x0000000183531c3c -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 140
	8   WhereToKit                           0x00000001005e6360 -[NBPhoneNumberUtil matchesEntirely:string:] (NBPhoneNumberUtil.m:3850)
	9   WhereToKit                           0x00000001005e0c28 -[NBPhoneNumberUtil isNumberMatchingDesc:numberDesc:] (NBPhoneNumberUtil.m:2255)
	10  WhereToKit                           0x00000001005e0628 -[NBPhoneNumberUtil getNumberTypeHelper:metadata:] (NBPhoneNumberUtil.m:2146)
	11  WhereToKit                           0x00000001005e0e90 -[NBPhoneNumberUtil isValidNumberForRegion:regionCode:] (NBPhoneNumberUtil.m:2322)
	12  WhereToKit                           0x00000 001005e0ca4 -[NBPhoneNumberUtil isValidNumber:] (NBPhoneNumberUtil.m:2273)

This is the crashing thread where I just finished using `NBPhoneNumberUtil`:

	Thread 20 Crashed:
	0   libobjc.A.dylib                      0x0000000193eebf04 objc_destructInstance + 40
	1   libobjc.A.dylib                      0x0000000193eebf90 object_dispose + 24
	2   libobjc.A.dylib                      0x0000000193ef8e28 objc_object::sidetable_release(bool) + 224
	3   WhereToKit                           0x00000001003c2724 -[NSString(Additions) isValidPhoneNumberCountryCode:] (NSString+Additions.m:142)

Here's the general crash information:

    Exception Type:  SIGSEGV
    Exception Codes: SEGV_ACCERR at 0x1a50093358c
    Crashed Thread:  20
    
    Application Specific Information:
    Selector name found in current argument registers: dealloc

Is the use of libPhoneNumber from multiple threads not supported? The recent refactoring of moving away from the singleton suggested to me that it's fine to use it from multiple threads as long as the `NBPhoneNumberUtil` objects are not shared.

**Comment by iziz** [comment]
I see.. maybe it cause from static function (nsregularexpression)
I'll find out the reason and fix it ASAP.

**Comment by futuretap** [comment]
That makes sense. Just after posting this I saw another crash, this time crashing in libicucore:

	Thread 9 Crashed:
	0   libsystem_kernel.dylib               0x0000000198cc7270 __pthread_kill + 8
	1   libsystem_pthread.dylib              0x0000000198d65170 pthread_kill + 108
	2   libsystem_c.dylib                    0x0000000198c3eb18 abort + 108
	3   libsystem_malloc.dylib               0x0000000198d023e4 nanozone_error + 316
	4   libsystem_malloc.dylib               0x0000000198d02550 _nano_malloc_check_clear + 360
	5   libsystem_malloc.dylib               0x0000000198d01064 nano_malloc + 40
	6   libsystem_malloc.dylib               0x0000000198cf13e4 malloc_zone_malloc + 112
	7   libsystem_malloc.dylib               0x0000000198cf5a04 malloc + 52
	8   libicucore.A.dylib                   0x0000000197f36664 icu::UnicodeSet::UnicodeSet() + 104
	9   libicucore.A.dylib                   0x0000000197ff8214 icu::RuleBasedTimeZone::getLocalDelta(int, int, int, int, int, int) const + 7076
	10  libicucore.A.dylib                   0x0000000197ff6afc icu::RuleBasedTimeZone::getLocalDelta(int, int, int, int, int, int) const + 1164
	11  libicucore.A.dylib                   0x000000019800ecb8 icu::RegexPattern::compile(UText*, unsigned int, UParseError&, UErrorCode&) + 280
	12  libicucore.A.dylib                   0x000000019804d174 uregex_open + 336
	13  Foundation                           0x0000000187b79a34 -[NSRegularExpression initWithPattern:options:error:] + 400
	14  Foundation                           0x0000000187c885d4 +[NSRegularExpression regularExpressionWithPattern:options:error:] + 68
	15  WhereToKit                           0x00000001005b0948 -[NBPhoneNumberUtil regularExpressionWithPattern:options:error:] (NBPhoneNumberUtil.m:167)
	16  WhereToKit                           0x00000001005b07bc -[NBPhoneNumberUtil entireRegularExpressionWithPattern:options:error:] (NBPhoneNumberUtil.m:144)
	17  WhereToKit                           0x00000001005be318 -[NBPhoneNumberUtil matchesEntirely:string:] (NBPhoneNumberUtil.m:3848)
	18  WhereToKit                           0x00000001005b8c28 -[NBPhoneNumberUtil isNumberMatchingDesc:numberDesc:] (NBPhoneNumberUtil.m:2255)
	19  WhereToKit                           0x00000001005b890c -[NBPhoneNumberUtil getNumberTypeHelper:metadata:] (NBPhoneNumberUtil.m:2209)
	20  WhereToKit                           0x00000001005b924c -[NBPhoneNumberUtil getRegionCodeForNumberFromRegionList:regionCodes:] (NBPhoneNumberUtil.m:2377)
	21  WhereToKit                           0x00000001005b9034 -[NBPhoneNumberUtil getRegionCodeForNumber:] (NBPhoneNumberUtil.m:2350)
	22  WhereToKit                           0x00000001005b8c7c -[NBPhoneNumberUtil isValidNumber:] (NBPhoneNumberUtil.m:2272)

There was also another active thread in the crash log that had accessed libPhoneNumber before.

Thanks for looking into this.

**Comment by iziz** [comment]
Thank you. and sorry for "not safe" multile thread issue. :)

**Comment by iziz** [comment]
Please check with latest code. I removed static NSRegularExpressions.

**Comment by futuretap** [comment]
Thanks. I'll integrate the code and ship the next update with it. Should I see any crashes, I'll let you know!

**Comment by iziz** [comment]
OK, Thank you very much.

**Comment by futuretap** [comment]
So I shipped the update and received one crash report so far, caused by NBPhoneNumberUtil:

	Thread 13 Crashed:
	0   libsystem_kernel.dylib               0x0000000195373270 __pthread_kill + 8
	1   libsystem_pthread.dylib              0x0000000195411170 pthread_kill + 108
	2   libsystem_c.dylib                    0x00000001952eab18 abort + 108
	3   libsystem_malloc.dylib               0x00000001953ae3e4 nanozone_error + 316
	4   libsystem_malloc.dylib               0x00000001953ae550 _nano_malloc_check_clear + 360
	5   libsystem_malloc.dylib               0x00000001953ad064 nano_malloc + 40
	6   libsystem_malloc.dylib               0x000000019539d3e4 malloc_zone_malloc + 112
	7   libsystem_malloc.dylib               0x00000001953a1a04 malloc + 52
	8   libicucore.A.dylib                   0x00000001945e2664 icu::UnicodeSet::UnicodeSet() + 104
	9   libicucore.A.dylib                   0x00000001946a4214 icu::RuleBasedTimeZone::getLocalDelta(int, int, int, int, int, int) const + 7076
	10  libicucore.A.dylib                   0x00000001946a2afc icu::RuleBasedTimeZone::getLocalDelta(int, int, int, int, int, int) const + 1164
	11  libicucore.A.dylib                   0x00000001946bacb8 icu::RegexPattern::compile(UText*, unsigned int, UParseError&, UErrorCode&) + 280
	12  libicucore.A.dylib                   0x00000001946f9174 uregex_open + 336
	13  Foundation                           0x0000000184225a34 -[NSRegularExpression initWithPattern:options:error:] + 400
	14  Foundation                           0x00000001843345d4 +[NSRegularExpression regularExpressionWithPattern:options:error:] + 68
	15  WhereToKit                           0x00000001006184d4 -[NBPhoneNumberUtil regularExpressionWithPattern:options:error:] (NBPhoneNumberUtil.m:167)
	16  WhereToKit                           0x0000000100618a38 -[NBPhoneNumberUtil replaceStringByRegex:regex:withTemplate:] (NBPhoneNumberUtil.m:242)
	17  WhereToKit                           0x000000010061a9ac -[NBPhoneNumberUtil extractPossibleNumber:] (NBPhoneNumberUtil.m:530)
	18  WhereToKit                           0x0000000100624d64 -[NBPhoneNumberUtil buildNationalNumberForParsing:nationalNumber:] (NBPhoneNumberUtil.m:3583)
	19  WhereToKit                           0x00000001006240f4 -[NBPhoneNumberUtil parseHelper:defaultRegion:keepRawInput:checkRegion:error:] (NBPhoneNumberUtil.m:3391)
	20  WhereToKit                           0x00000001006239e0 -[NBPhoneNumberUtil parse:defaultRegion:error:] (NBPhoneNumberUtil.m:3251)

Looks like the exact same backtrace. This time, there was no other active thread using NBPhoneNumberUtil, though.

**Comment by iziz** [comment]
I'm afraid that, but I can't raise that crash.
Could you tell me your execution environment ?
and, see below... (my test code)

```
- (NSString *)stringWithRandomNumber
{
    NSString *numbers = @"0123456789";
    NSMutableString *randomString = [NSMutableString stringWithCapacity:11];
    
    for (int i=0; i<12; i++) {
        [randomString appendFormat: @"%C", [numbers characterAtIndex: arc4random() % [numbers length]]];
    }
    
    return randomString;
}


- (NSString *)randomRegion
{
    NBMetadataHelper *aHelper = [[NBMetadataHelper alloc] init];
    NSDictionary *metadata = [[aHelper getAllMetadata] objectAtIndex:(arc4random() % [aHelper getAllMetadata].count)];
    if (metadata) {
        NSString *region = [metadata objectForKey:@"code"];
        if (region) {
            return region;
        }
    }
    
    return nil;
}


- (void)testForMultithread
{
    NBPhoneNumberUtil *aUtil = [[NBPhoneNumberUtil alloc] init];
    NSString *testRegion = [self randomRegion];
    
    if (!testRegion) {
        return;
    }
    
    NSLog(@"- START [%@]", testRegion);
    
    dispatch_async(dispatch_get_main_queue(), ^{
        NSError *error = nil;
        
        for (int i=0; i<1000; i++) {
            [aUtil parse:[self stringWithRandomNumber] defaultRegion:testRegion error:&error];
            if (error && ![error.domain isEqualToString:@"INVALID_COUNTRY_CODE"]) {
                NSLog(@"error [%@]", [error localizedDescription]);
            }
            error = nil;
        }
        
        NSLog(@"OK [%@]", testRegion);
    });
}


- (void)testWithGCD
{
    for (int i = 0; i<1000; i++) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
            [self testForMultithread];
        });
    }
}
```

**Comment by futuretap** [comment]
I'm creating (and releasing) my `NBPhoneNumberUtil` objects on the fly on a background thread. Looking over your tests, it seems you're running `-parse:` completely on the main thread, no? 

I'll probably have to write some concurrency tests for my use case…

**Comment by iziz** [comment]
Yes, please show me. I will test it.
