### ISSUE TITLE
iOS 8.1 no country name

### ISSUE THREAD

**Issue by medisean** [iziz/libPhoneNumber-iOS#72]
In iOS 8.1. I can't get country name. Please help me to fix it. Thank you. Code as follow:

NBMetadataHelper.m
NSString *country = [[NSLocale currentLocale] displayNameForKey:NSLocaleIdentifier value:identifier];
// country is nil.

**Comment by medisean** [comment]
It seems a iOS system bug.

**Comment by iziz** [comment]
Maybe it will helps...
```
    NSLocale *localLocale = [NSLocale currentLocale];
    return [localLocale objectForKey:NSLocaleCountryCode];
```
or use telephone sim locale.

**Comment by medisean** [comment]
It's value is also nil in iOS 8.1.

**Comment by medisean** [comment]
Right now, I got a answer. In iOS 8.1, If the country's name is nil. Just return it's country code. It may be more kind to user.

**Comment by iziz** [comment]
OK~
