### ISSUE TITLE
Phone number edit

### ISSUE THREAD

**Issue by arietis** [iziz/libPhoneNumber-iOS#73]
Hello!
Is there any good solution to edit formatted phone number inside UITextField? I'm currently using such solution http://stackoverflow.com/a/28321180/837794 but the only things you can do is add digit or remove digit which is not flexible way to edit numbers. :)
Thanks!

**Comment by iziz** [comment]
Below code works fine. But it need to more exception code... :)
```
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
    NSString *textFieldString = [[textField text] stringByReplacingCharactersInRange:range withString:string];
    
    NSString *rawString = [textFieldString stringByReplacingOccurrencesOfString:@" " withString:@""];
    rawString = [textFieldString stringByReplacingOccurrencesOfString:@"-" withString:@""];
    
    NBAsYouTypeFormatter *aFormatter = [[NBAsYouTypeFormatter alloc] initWithRegionCode:@"KR"];
    NSString *formattedString = [aFormatter inputString:rawString];
    
    if (aFormatter.isSuccessfulFormatting) {
        textField.text = formattedString;
    } else {
        textField.text = textFieldString;
    }
    
    return NO;
}
```

**Comment by jensmoes** [comment]
This will not work if you delete a formatting character mid text. In that case nothing will happen.
Expected result is the next valid phone number character to the left of it should be deleted.
Is this possible without using the range as also suggested here https://github.com/iziz/libPhoneNumber-iOS/issues/43 ?

**Comment by iziz** [comment]
https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber-iOS/NBTextField.swift
