### ISSUE TITLE
Use of unresolved identifier 'NBPhoneNumberUtil'

### ISSUE THREAD

**Issue by lowki93** [iziz/libPhoneNumber-iOS#75]
Hi, 

I used your sample code to integrate your library in swift but i have this problem : 
<img width="936" alt="capture d ecran 2015-07-24 a 12 30 13" src="https://cloud.githubusercontent.com/assets/5473017/8882915/c50b70c4-31ff-11e5-8423-b32838b16f2a.png">

**Comment by iziz** [comment]
See below link :)

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID124

**Comment by lowki93** [comment]
Hello :).
my Bridging-header is right. I use it with Gossip Library.

I add this 2 link in bridging-header : 
#import <libPhoneNumber_iOS/NBPhoneNumberUtil.h>
#import <libPhoneNumber_iOS/NBPhoneNumber.h>

And after I have the error as above :(.

I due forgotten something but I don't see him and I followed your tutorial to the letter

**Comment by iziz** [comment]
Did you check "Full path" in your bridging-header ?

**Comment by lowki93** [comment]
Yes.
I used pod to importe your dependencies and it don't work. I copy the source that pod load. I import it in Xcode and it works. It's weird ...

**Comment by iziz** [comment]
Could you show me your sample project ?

**Comment by iziz** [comment]
In "...Beidging-Header.h"
```
#import "libPhoneNumber-iOS/NBPhoneNumberUtil.h"
#import "libPhoneNumber-iOS/NBPhoneNumber.h"
```

In AppDelegate.swift
```
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        let phoneUtil = NBPhoneNumberUtil()

        var errorPointer:NSError?
        var number:NBPhoneNumber = phoneUtil.parse("01041241282", defaultRegion:"KR", error:&errorPointer)

        NSLog("%@", number)

        return true
    }
```

Works fine now with cocoapods.

**Comment by lowki93** [comment]
No you're wrong.
it's : 
#import "libPhoneNumber_iOS/NBPhoneNumberUtil.h"
#import "libPhoneNumber_iOS/NBPhoneNumber.h"

and this doesn't work too

**Comment by iziz** [comment]
It's path will be change.

**Comment by esetnik** [comment]
@iziz i'm having the same issue as @lowki93 :(

```
#import "libPhoneNumber_iOS/NBPhoneNumber.h"
#import "libPhoneNumber_iOS/NBPhoneNumberUtil.h"
```

**Comment by lowki93** [comment]
@esetnik 
u're using pods or you clone this project ?

**Comment by esetnik** [comment]
I am using pods:

`pod 'libPhoneNumber-iOS', '0.8.7'`

**Comment by lowki93** [comment]
Don't use pods, I had the same problem few days ago.
Clone this projet, and import the folder which containts the library in your project.
In your bridgingHeader add this : 

#import "NBPhoneNumberUtil.h"
#import "NBPhoneNumber.h"
#import "NBAsYouTypeFormatter.h"

and normally, it's working

**Comment by esetnik** [comment]
@lowki93 that's not really a solution for me. I prefer to only use versioned dependencies in my projects.

**Comment by lowki93** [comment]
i try with pods for 1 week, this is the only solution i find. Me too i prefer use versioned dependencies, but if it don't work, you are a another solution

**Comment by esetnik** [comment]
Thanks for your tip, i'll try to work with @iziz to come up with a fix for the cocoapods issue.

**Comment by lowki93** [comment]
No problem, tell when you fix the problem.
Thanks

**Comment by iziz** [comment]
Ah, Did you tried "use_frameworks!" option for your Podfile ?

**Comment by lowki93** [comment]
I already use it

**Comment by esetnik** [comment]
Yes I am also using the `use_frameworks!` flag

**Comment by asheinfeld** [comment]
+1 I'm having the same exact problem here.

**Comment by dkharrat** [comment]
I have the same issue. Not sure why it's needed, but I fixed it by importing:

    import libPhoneNumber_iOS.NBPhoneNumberUtil

**Comment by esetnik** [comment]
Similarly I was able to fix it by `import libPhoneNumber_iOS` in my swift file.

**Comment by VivienCormier** [comment]
I had the same issue but in my case, I fixed it by adding the pods to the Unit test's target as well.


target :Projet do
	pod 'libPhoneNumber-iOS'
end

target :ProjetTests do
	pod 'libPhoneNumber-iOS'
end


I was trying to use the libPoneNumber inside a file that was also inside the target "ProjetTests".

**Comment by isacikgoz** [comment]
The issue seems to be related with underscore issue of cocoapods. importing as `libPhoneNumber_iOS` solves the problem.

**Comment by Artimuss** [comment]
`import libPhoneNumber_iOS` doesn't work for me.
I've got the error `No such module 'libPhoneNumber_iOS'`. I have made an install from CocoaPods

Any idea ?

**Comment by rlaferla** [comment]
I really hate CocoaPods when it comes to importing headers and GitHub projects that don't clearly show the import statements for headers you need to import in the README and examples.
