### ISSUE TITLE
Suport for getSupportedRegions

### ISSUE THREAD

**Issue by TiagoVeloso** [iziz/libPhoneNumber-iOS#76]
Is there any chance we can get this method supported?

**Comment by iziz** [comment]
Fix with isNaN

**Comment by TiagoVeloso** [comment]
Have you considered using the `isnan(x)` define function in math.h?

**Comment by iziz** [comment]
I don't know how, do you have any idea using 'isnan' in math.h ?

**Comment by TiagoVeloso** [comment]
It seems it can't be used with Strings as you use it. Only float, double and long.

Sorry for the missunderstanding.

**Comment by iziz** [comment]
Nop :)

**Comment by TiagoVeloso** [comment]
To use with strings I've seen some people using NSNumberFormatter to parse a string to a NSNumber, it supposedly handles the case where the string is no numeric.

I am not sure if that's a good approach though.

I was just suggesting to see if this could improve performance a bit.

**Comment by iziz** [comment]
OK I see. I will update later.

**Comment by iziz** [comment]
```
NSCharacterSet* notDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
if ([newString rangeOfCharacterFromSet:notDigits].location == NSNotFound)
{
    // newString consists only of the digits 0 through 9
}
```
