### ISSUE TITLE
Swift libPhoneNumber-iOS -> libPhoneNumber_iOS

### ISSUE THREAD

**Issue by gbrhaz** [iziz/libPhoneNumber-iOS#78]
Not sure what the correct solution is with importing frameworks in Swift now, but hyphens aren't allowed, and they get changed to underscores instead. Should this library be renamed? Or should it be something easier such as writing in the README that this is what will happen?

**Comment by iziz** [comment]
FYI : https://github.com/iziz/libPhoneNumber-iOS/issues/70

Maybe I should create wrapped swift class for libphonenumber-iOS soon. :)

**Comment by iziz** [comment]
And
http://stackoverflow.com/questions/24122914/how-to-integrate-cocoapods-with-a-swift-project
will helps~

**Comment by iziz** [comment]
If you still suffering problem, then please open this issue.
