### ISSUE TITLE
Carthage not working

### ISSUE THREAD

**Issue by kylejm** [iziz/libPhoneNumber-iOS#81]
Possibly because the target is not a Framework?

**Comment by kylejm** [comment]
I've noticed that this has in PR #79. Can you make a release pretty please? :blush:

**Comment by iziz** [comment]
OK I will check and fix it.

**Comment by iziz** [comment]
Now working fine with Update Cocoapods version (0.8.7) :)

**Comment by kylejm** [comment]
Awesome! Thank you! 😁
