### ISSUE TITLE
Cocoapod support and Carthage support no longer work properly together

### ISSUE THREAD

**Issue by simX** [iziz/libPhoneNumber-iOS#86]
I had a pull request merged into libPhoneNumber-iOS a while ago that added Carthage support, and allowed Carthage and Cocoapod support to coexist together easily in the same codebase.  However, that's been reverted by https://github.com/iziz/libPhoneNumber-iOS/pull/63

Now, if I want to use Cocoapods and Carthage in the same project, I can no longer use the same syntax for both Cocoapods and Carthage.  With my pull request, you could use "#import \<libPhoneNumber/libPhoneNumber.h\>" regardless of which package manager you were using.  Now you cannot.

What's the reasoning for the change?  This is extremely annoying.  I don't want to put #ifdefs all over my project whenever I want to use libphonenumber.

**Comment by iziz** [comment]
Would you give me more detail in "I can no longer use the same syntax for both Cocoapods and Carthage. " ?

**Comment by simX** [comment]
Because the pod spec is called "libPhoneNumber-iOS", I have to use #import \<libPhoneNumber-iOS/libPhoneNumber.h\> when using Cocoapods.  But because frameworks don't support dashes in their name, I have to use #import \<libPhoneNumber/libPhoneNumber.h\> when using Carthage.  I don't want to spread macros or ifdefs all over my code every time I want to import the libPhoneNumber project, since I have to support both Cocoapods and Carthage still.

**Comment by iziz** [comment]
Ah, I see... "libPhoneNumber-iOS" is registered name in Cocoapods. 
So, all programmers who using "libPhoneNumber-iOS" will have update problems.

Do you have any idea for solve that ? (I have no idea)

And, I have wondering that why are you use libPhoneNumber-iOS with Cocoapods and Carthage together in own project ?

**Comment by simX** [comment]
We have to support both because our app on the App Store still has to support iOS 7.  But internally, using Carthage is so much easier because internal users don't have to mess with Cocoapods.

Unfortunately, I know of no way to do this, other than to change the name of the Cocoapods spec (which usually doesn't include "-iOS" anyway).  Maybe the Cocoapods central repo has an internal way to mark a certain pod spec name as an alias of another?  Maybe worth opening an issue with them?

**Comment by iziz** [comment]
Do you know how to mark a certain pod spec name as an alias of another ?

Anyway, I think you can change your Podfile.
(May below link helps)
https://gist.github.com/daltonclaybrook/e109033af85e6efd6972

**Comment by iziz** [comment]
And you can add pod/... in "include path"
