### ISSUE TITLE
Missing prefix for UM (US Outlying Islands)

### ISSUE THREAD

**Issue by johnmengqin** [iziz/libPhoneNumber-iOS#87]
http://www.auslandsvorwahlen.net/en/country/268

kMapCCode2CN in NBMetadataHelper  is missing  object + key pair  {"1", "UM"}

**Comment by iziz** [comment]
libPhoneNumber-iOS using https://github.com/googlei18n/libphonenumber metadata.
So, would you create issue to https://github.com/googlei18n/libphonenumber
