### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by vanhung504** [iziz/libPhoneNumber-iOS#90]
@iziz I use your lib for my project by swift language. I had add all your lib file in libPhoneNumber folder to my project and add Bridging-Header. All fine but when i build project clang show error:

<img width="840" alt="screen shot 2015-10-04 at 9 56 33 pm" src="https://cloud.githubusercontent.com/assets/8073806/10268445/d6dca0cc-6ae2-11e5-9b82-95c77824001f.png">

**Comment by iziz** [comment]
I think you should check your build settings. ("Build Active Architecture Only")
