### ISSUE TITLE
How to use in swift 2.0?

### ISSUE THREAD

**Issue by jimAnderson007** [iziz/libPhoneNumber-iOS#91]
I have added pod successfully.

Add header file to bridge.
Now, I write below code get error in second line
 let phoneUtil = NBPhoneNumberUtil.sharedInstance()
   let number:NBPhoneNumber = phoneUtil.parse("123", defaultRegion: "US")

Error: call can throw,but it is not marked with "try" and the error is not handle
could any one help me out?

**Comment by iziz** [comment]
Updated readme
