### ISSUE TITLE
Update to last metadata

### ISSUE THREAD

**Issue by juancazalla** [iziz/libPhoneNumber-iOS#92]
Can you update to the latest metadata?

**Comment by iziz** [comment]
OK
Now, released 0.8.8

**Comment by juancazalla** [comment]
Great!

thanks!

**Comment by juancazalla** [comment]
You are amazing!

Can you generate a version with this metadata https://www.dropbox.com/s/kqnjg1cl21r9qr4/PhoneNumberMetaData.xml?dl=0?

This metadata will be updated in the next days. Or can you explain me how can I do it?

**Comment by iziz** [comment]
Hmm, Creating metadata classes is very simple, but it must be in "google libphonenumber" metadata.js files. so, maybe you should wait for it's release.

Anyway, I can update metadata anytime. But updating version for cocoapods may not :)

**Comment by juancazalla** [comment]
So, I can't update to the link metadata manually, correct?

**Comment by iziz** [comment]
You can update metadata using google libphonenumber "metadata.js" file. but "PhoneNumberMetaData.xml" cant.

**Comment by juancazalla** [comment]
do you think we could use the phps in the Test folder and point them to a local repository we could create the metadata ourselves?

**Comment by iziz** [comment]
Maybe yes, so you want to update metadata and creating pull request ?

**Comment by juancazalla** [comment]
No, I would like update locally only, the lib is all ok

**Comment by juancazalla** [comment]
How can I support you?

**Comment by iziz** [comment]
Sorry what's mean "support me" ? :)

**Comment by juancazalla** [comment]
Help you with something, money or many stars!

**Comment by juancazalla** [comment]
I'm still don't know where I need to put the metadata, can you help me?

**Comment by iziz** [comment]
Ah, it(libphonenumber-ios) is just for my enjoyment. don't worry about that.
And, if you want to update metadata locally, edit "NBMetadataCore.m"

**Comment by juancazalla** [comment]
Great! Thanks! You are amazing! 

It works!
