### ISSUE TITLE
Update Podspec to support watchOS 2

### ISSUE THREAD

**Issue by Changsung** [iziz/libPhoneNumber-iOS#93]
When using libPhoneNumber-iOS with watchOS 2, then I get error message when running pod install

Please update the podspec for libPhoneNumber-iOS to support watchOS 2.

like here 

Pod::Spec.new do |s|
  s.watchos.deployment_target = '2.0'
end

thanks !

**Comment by iziz** [comment]
Thanks, but please leave version to 0.8.8. It will update next update cycle/
