### ISSUE TITLE
There is an issue with isNANPACountry.

### ISSUE THREAD

**Issue by ryanle-gamo** [iziz/libPhoneNumber-iOS#97]
I entered US number +1 3472251240. It meant that country code is +1 and phone number is 3472251240. but when I display it, country code is +1347 and phone number is 2251240. This is first time I use it, so I don't know where the bug comes. The following is my code:

NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
NSString *nationalNumber = nil;
NSNumber *extractCountryCode = [phoneUtil extractCountryCode:customer.phone nationalNumber:&nationalNumber];
NSString *regionCode = [phoneUtil getRegionCodeForCountryCode:extractCountryCode];
if ([phoneUtil isNANPACountry:regionCode])
{
regionCode = [customer.phone substringToIndex:5];
}
else
{
NSDictionary *codes = [NSDictionary dictionaryWithPhoneCountryCodes];
regionCode = [codes objectForKey:regionCode];
}
NSString *phoneNumber = [customer.phone substringFromIndex:regionCode.length];
[self setCountryCode:regionCode];
[self setText:phoneNumber];

This is urgent at my situation. If anyone has any ideas, please give to me.
Thanks you!

**Comment by dlyongemallo** [comment]
As I said in googlei18n/libphonenumber#881, it seems that you are explicitly extracting the first 5 characters ("+1347") with the lines:
regionCode = [customer.phone substringToIndex:5];
NSString *phoneNumber = [customer.phone substringFromIndex:regionCode.length];

**Comment by iziz** [comment]
See this https://github.com/iziz/libPhoneNumber-iOS/issues/74

**Comment by iziz** [comment]
Or.. you should export country code from SIM info or locale info.
