### ISSUE TITLE
Am I using the parser correctly or not? Validation issue.

### ISSUE THREAD

**Issue by ClockWise89** [iziz/libPhoneNumber-iOS#98]
My question is simply how the <code>public func parse(numberToParse: String!, defaultRegion: String!) throws -> NBPhoneNumber</code> works? More specifically, I'm having a parsing issue in my app. When the user enters numbers it's all fine, but if the user starts adding letters the validation is suddenly not working so great anymore. The user can add up to two letters and the parser will still return a correct <code>NBPhoneNumber</code>, unless the user adds the letter "ö" which, for some reason, will always return a validated <code>NBPhoneNumber</code>.

Clarification: If the user enters "0706348441ee" the parser will return "0706348441", but if the user enters "0706348441eee" it will return "070634844133", which is too long for a number of my region thus failing validation. Or the user can enter "0706348441öööööööööööööööööööö" which will return just the numbers. The discomforting part is mainly that if you feed the parser letters it will start returning numbers, how can three "e"'s turn into the number 33?

So my question is wether you are supposed to send in the user's entered value to the parser, or if you are supposed to send it numbers only?

My snippet of code:
<code>
func validate(value: String?) -> Bool {
    
        var valid = false
        
        do {
            let phoneUtil = NBPhoneNumberUtil()
            let phoneNumber = try phoneUtil.parse(value, defaultRegion: "SE")
            valid = phoneUtil.isValidNumberForRegion(phoneNumber, regionCode: "SE")
        }
        catch let error as NSError {
            logger.debug(error.localizedDescription)
        }
        
        return valid
    }

</code>

Thanks!

**Comment by iziz** [comment]
libphonenumber can parse character as phonenumber

EX>
```
NBPhoneNumber *tollfreeNumber = [[NBPhoneNumber alloc] init];
[tollfreeNumber setCountryCode:@64];
[tollfreeNumber setNationalNumber:@800332005];
XCTAssertTrue([tollfreeNumber isEqual:[_aUtil parse:@"0800 DDA 005" defaultRegion:@"NZ" error:&anError]]);
```

You can test it using libphonenumber's demo page.
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

And, how about to use below methods ?
- (NSString*)normalizePhoneNumber:(NSString*)phoneNumber;
- (NSString*)normalizeDigitsOnly:(NSString*)number;

**Comment by ClockWise89** [comment]
Thanks, that's exactly what I was looking for. Will rewrite my validation a bit then, thanks for the quick response! :)
